import AxeBuilder from '@axe-core/playwright';
import { expect, test, type Page } from '@playwright/test';
const WS = '01JB000000000000000WSP0001';
const HUB = process.env.E2E_HUB_URL ?? `http://127.0.0.1:${process.env.E2E_HUB_PORT ?? 47482}`;
const headers = { Authorization: `Bearer ${process.env.E2E_HUB_TOKEN ?? 'dev-device-token'}` };
async function open(page: Page, item: string, title: string) {
  await page.getByRole('button', { name: 'New', exact: true }).click();
  await page.getByRole('menuitem', { name: item, exact: true }).click();
  const dialog = page.getByRole('dialog', { name: title, exact: true });
  await expect(dialog.getByLabel('Name', { exact: true })).toBeFocused();
  return dialog;
}
for (const theme of ['light', 'dark'] as const) {
  test(`create every entity with inline validation, focus and live lists in ${theme}`, async ({ page, request }) => {
    test.setTimeout(120_000);
    const tag = theme === 'light' ? 'LT' : 'DK';
    const key = `CR${tag}`;
    const workspace = await (await request.get(`${HUB}/v1/workspace`, { headers })).json() as { workspace: { id: string } };
    const ws = workspace.workspace.id || WS;
    await page.goto(`/w/${ws}/members`);
    await page.getByRole('radio', { name: theme === 'light' ? 'Light' : 'Dark', exact: true }).click();
    let dialog = await open(page, 'Agent', 'New agent');
    await expect(dialog.getByLabel('Name', { exact: true })).toBeFocused();
    await dialog.getByLabel('Name', { exact: true }).fill(`Synthetic agent ${tag}`);
    await dialog.getByLabel('Engine', { exact: true }).selectOption('codex');
    await dialog.getByLabel('Instructions (optional)', { exact: true }).fill('Use synthetic examples.');
    expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([]);
    await dialog.getByRole('button', { name: 'Create', exact: true }).click();
    await expect(dialog).toHaveCount(0);
    await expect(page.getByRole('region', { name: 'Agent recipes' }).getByText(`Synthetic agent ${tag} · codex`)).toBeVisible();
    await expect(page.getByRole('button', { name: 'New', exact: true })).toBeFocused();
    dialog = await open(page, 'Team', 'New team');
    await dialog.getByLabel('Name', { exact: true }).fill(`Synthetic crew ${tag}`);
    await dialog.getByRole('checkbox', { name: `Synthetic agent ${tag} (agent)`, exact: true }).check();
    expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([]);
    await dialog.getByRole('button', { name: 'Create', exact: true }).click();
    await expect(dialog).toHaveCount(0);
    await expect(page.getByRole('region', { name: 'Teams' }).getByText(new RegExp(`Synthetic crew ${tag}`))).toBeVisible();
    dialog = await open(page, 'Project', 'New project');
    await dialog.getByLabel('Name', { exact: true }).fill(`Synthetic project ${tag}`);
    await dialog.getByLabel('Key', { exact: true }).fill('PAP');
    await dialog.getByLabel('Root path', { exact: true }).fill('relative/path');
    await dialog.getByLabel('First workstream (optional)', { exact: true }).fill(`First stream ${tag}`);
    await dialog.getByRole('button', { name: 'Create', exact: true }).click();
    await expect(dialog.getByRole('alert')).toContainText('absolute path');
    const machineResponse = await request.get(`${HUB}/v1/machines`, { headers });
    const machines = await machineResponse.json() as { id: string; kind: string; info?: { os: string } }[];
    const selected = await dialog.getByLabel('Machine', { exact: true }).inputValue();
    const machine = machines.find((m) => m.id === selected);
    await dialog.getByLabel('Root path', { exact: true }).fill(machine?.info?.os === 'windows' ? 'C:\\demo\\synthetic' : '/home/sam/synthetic');
    await dialog.getByRole('button', { name: 'Create', exact: true }).click();
    await expect(dialog.getByRole('alert')).toContainText('PAP');
    await dialog.getByLabel('Key', { exact: true }).fill(key);
    expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([]);
    await dialog.getByRole('button', { name: 'Create', exact: true }).click();
    await expect(page.getByRole('heading', { level: 1, name: `Synthetic project ${tag}`, exact: true })).toBeVisible();
    await page.getByRole('radio', { name: 'Workstreams', exact: true }).click();
    await expect(page.getByRole('button', { name: `First stream ${tag}`, exact: true })).toBeVisible();
    await page.getByRole('button', { name: 'New', exact: true }).click();
    await expect(page.getByRole('menuitem', { name: 'Workstream', exact: true })).toBeVisible();
    await page.keyboard.press('Escape');
    await page.getByRole('button', { name: 'New workstream', exact: true }).click();
    dialog = page.getByRole('dialog', { name: 'New workstream', exact: true });
    await dialog.getByLabel('Name', { exact: true }).fill(`Second stream ${tag}`);
    expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([]);
    await dialog.getByRole('button', { name: 'Create', exact: true }).click();
    await expect(page.getByRole('heading', { level: 1, name: `Second stream ${tag}`, exact: true })).toBeVisible();
    // The palette reaches the same forms and Escape restores the original keyboard target.
    const trigger = page.getByRole('button', { name: 'New', exact: true });
    await trigger.focus(); await page.keyboard.press('Control+KeyK');
    await page.getByRole('combobox', { name: 'Search' }).fill('new agent');
    await page.getByRole('option').first().click();
    await expect(page.getByRole('dialog', { name: 'New agent' })).toBeVisible();
    await page.keyboard.press('Escape'); await expect(trigger).toBeFocused();
    const personas = await (await request.get(`${HUB}/v1/personas`, { headers })).json() as { id: string; name: string }[];
    const members = await (await request.get(`${HUB}/v1/members`, { headers })).json() as { id: string; persona?: string }[];
    const recipe = personas.find((p) => p.name === `Synthetic agent ${tag}`);
    const member = members.find((m) => m.persona === recipe?.id);
    expect(member).toBeDefined();
    await page.goto(`/w/${ws}/tasks/01JB000000000000000TSK0002`);
    const dispatch = page.getByRole('combobox', { name: 'Dispatch to', exact: true });
    await expect(dispatch.getByRole('option', { name: new RegExp(`Synthetic agent ${tag}`) })).toHaveAttribute('value', member?.id ?? 'missing');
    await expect(dispatch.getByRole('option', { name: /@office|@sync/ })).toHaveCount(0);
  });
}
