//! One Claude Code JSONL record to [`TranscriptItem`]s and session facts.
//!
//! Context-free on purpose: a record's items depend only on its own line, so forward reads,
//! backward pages and fuzzing all see the same thing. The one cross-record rule (a turn-duration
//! record after `end_turn` must not end the turn twice) is applied by the caller through
//! [`ClaudeRecord::soft_turn_end`].

use crate::lines::SkipReason;
use crate::text::{first_line, summary, title, truncate_chars};
use crate::time::parse_rfc3339_ms;
use pitcrew_interfaces::source::{PlanItem, PlanStatus, TranscriptItem};
use pitcrew_protocol::model::TimestampMs;
use serde_json::{Map, Value, json};

/// Longest prompt or assistant text kept, in characters.
const MAX_TEXT_CHARS: usize = 100_000;
/// Longest tool target, in characters.
const MAX_TARGET_CHARS: usize = 200;
/// Tool result summaries: this many lines, this many characters.
const SUMMARY_LINES: usize = 3;
const SUMMARY_CHARS: usize = 240;
/// Tool inputs: strings are cut to this many characters...
const MAX_INPUT_STRING_CHARS: usize = 1024;
/// ...and an input still larger than this (as JSON) is replaced by a preview.
const MAX_INPUT_JSON_BYTES: usize = 16 * 1024;
/// Longest diff kept, in bytes.
const MAX_DIFF_BYTES: usize = 64 * 1024;
/// Ids, model and branch longer than this (in bytes) are dropped as implausible.
const MAX_ID_BYTES: usize = 256;
/// A cwd or file path longer than this (in bytes) is dropped or cut.
const MAX_PATH_BYTES: usize = 4096;
/// Longest custom title or summary, in characters.
pub(crate) const MAX_TITLE_CHARS: usize = 120;
/// Tool names, in characters.
const MAX_TOOL_CHARS: usize = 100;
/// Plan lines: at most this many, each cut to this many characters.
const MAX_PLAN_ITEMS: usize = 200;
const MAX_PLAN_TEXT_CHARS: usize = 1000;
/// Questions: count per call, text, option count and option label length.
const MAX_QUESTIONS: usize = 20;
const MAX_QUESTION_CHARS: usize = 4000;
const MAX_OPTIONS: usize = 50;
const MAX_OPTION_CHARS: usize = 200;

/// Text blocks that Claude Code writes into user records but a person did not type.
const INJECTED_PREFIXES: &[&str] = &[
    "<command-name>",
    "<command-message>",
    "<command-args>",
    "<local-command-stdout>",
    "<local-command-stderr>",
    "<local-command-caveat>",
    "<system-reminder>",
    "<bash-input>",
    "<bash-stdout>",
    "<bash-stderr>",
    "[Request interrupted by user",
    "Caveat: The messages below were generated by the user while running local commands",
];

/// What one record contributes.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct ClaudeRecord {
    /// Items, in order.
    pub items: Vec<TranscriptItem>,
    /// Set for a turn-duration record. Its single `TurnEnded` is kept only when the item before
    /// it (in the whole transcript) exists and is not itself a `TurnEnded`.
    pub soft_turn_end: bool,
    /// Session facts found on the record.
    pub facts: RecordFacts,
}

/// Session facts one record carries.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct RecordFacts {
    /// `sessionId`.
    pub session_id: Option<String>,
    /// `agentId`, on sub-agent records.
    pub agent_id: Option<String>,
    /// `cwd`.
    pub cwd: Option<String>,
    /// `gitBranch`.
    pub branch: Option<String>,
    /// The assistant message's model.
    pub model: Option<String>,
    /// `timestamp`.
    pub timestamp: Option<TimestampMs>,
    /// `isSidechain`.
    pub is_sidechain: Option<bool>,
    /// A `custom-title` record's title.
    pub custom_title: Option<String>,
    /// A `summary` record's summary.
    pub summary: Option<String>,
}

/// Parses one line of a Claude Code transcript; `offset` is the line's byte offset.
///
/// Blank lines and records of unknown or wrong shape give no items. Only lines that are not
/// UTF-8, not JSON, or not a JSON object are errors, and callers skip them.
///
/// # Errors
///
/// The reason the line cannot be used.
pub fn parse_line(line: &[u8], offset: u64) -> Result<ClaudeRecord, SkipReason> {
    let text = std::str::from_utf8(line).map_err(|_| SkipReason::InvalidUtf8)?;
    if text.trim().is_empty() {
        return Ok(ClaudeRecord::default());
    }
    let value: Value =
        serde_json::from_str(text).map_err(|e| SkipReason::Malformed(e.to_string()))?;
    let Value::Object(rec) = value else {
        return Err(SkipReason::Malformed("not a JSON object".into()));
    };

    let mut out = ClaudeRecord {
        facts: facts(&rec),
        ..ClaudeRecord::default()
    };
    let at = out.facts.timestamp.unwrap_or(0);
    match str_at(&rec, "type") {
        Some("user") => user(&rec, at, offset, &mut out.items),
        Some("assistant") => assistant(&rec, at, offset, &mut out.items),
        Some("system") if str_at(&rec, "subtype") == Some("turn_duration") => {
            out.items.push(TranscriptItem::TurnEnded { at, offset });
            out.soft_turn_end = true;
        }
        _ => {}
    }
    Ok(out)
}

fn str_at<'a>(obj: &'a Map<String, Value>, key: &str) -> Option<&'a str> {
    obj.get(key).and_then(Value::as_str)
}

/// A trimmed, non-empty value no longer than `max` bytes; longer values are dropped, not cut,
/// because a cut id or path would name something else.
fn bounded(s: Option<&str>, max: usize) -> Option<String> {
    s.map(str::trim)
        .filter(|s| !s.is_empty() && s.len() <= max)
        .map(str::to_owned)
}

/// A title-like value: whitespace collapsed, cut to [`MAX_TITLE_CHARS`].
fn title_value(s: Option<&str>) -> Option<String> {
    s.map(|s| title(s, MAX_TITLE_CHARS))
        .filter(|s| !s.is_empty())
}

/// A call id, cut the same way on both the call and the result so they still pair.
fn call_id(s: &str) -> String {
    truncate_chars(s, MAX_ID_BYTES)
}

fn facts(rec: &Map<String, Value>) -> RecordFacts {
    let kind = str_at(rec, "type");
    let model = (kind == Some("assistant"))
        .then(|| {
            rec.get("message")
                .and_then(|m| m.get("model"))
                .and_then(Value::as_str)
        })
        .flatten()
        .filter(|m| !m.starts_with('<'));
    RecordFacts {
        session_id: bounded(str_at(rec, "sessionId"), MAX_ID_BYTES),
        agent_id: bounded(str_at(rec, "agentId"), MAX_ID_BYTES),
        cwd: bounded(str_at(rec, "cwd"), MAX_PATH_BYTES),
        branch: bounded(str_at(rec, "gitBranch"), MAX_ID_BYTES),
        model: bounded(model, MAX_ID_BYTES),
        timestamp: str_at(rec, "timestamp").and_then(parse_rfc3339_ms),
        is_sidechain: rec.get("isSidechain").and_then(Value::as_bool),
        custom_title: (kind == Some("custom-title"))
            .then(|| title_value(str_at(rec, "customTitle")))
            .flatten(),
        summary: (kind == Some("summary"))
            .then(|| title_value(str_at(rec, "summary")))
            .flatten(),
    }
}

fn user(rec: &Map<String, Value>, at: TimestampMs, offset: u64, out: &mut Vec<TranscriptItem>) {
    let flag = |k: &str| rec.get(k).and_then(Value::as_bool).unwrap_or(false);
    let injected = flag("isMeta") || flag("isCompactSummary") || flag("isVisibleInTranscriptOnly");
    let Some(content) = rec.get("message").and_then(|m| m.get("content")) else {
        return;
    };

    let mut texts: Vec<&str> = Vec::new();
    let mut had_result = false;
    match content {
        Value::String(s) => texts.push(s),
        Value::Array(blocks) => {
            for block in blocks {
                match block.get("type").and_then(Value::as_str) {
                    Some("text") => {
                        if let Some(t) = block.get("text").and_then(Value::as_str) {
                            texts.push(t);
                        }
                    }
                    Some("tool_result") => {
                        let Some(id) = block.get("tool_use_id").and_then(Value::as_str) else {
                            continue;
                        };
                        had_result = true;
                        out.push(TranscriptItem::ToolResult {
                            at,
                            call_id: call_id(id),
                            is_error: block
                                .get("is_error")
                                .and_then(Value::as_bool)
                                .unwrap_or(false),
                            summary: summary(
                                &content_text(block.get("content")),
                                SUMMARY_LINES,
                                SUMMARY_CHARS,
                            ),
                            offset,
                        });
                    }
                    _ => {}
                }
            }
        }
        _ => {}
    }

    if had_result {
        if let Some(edit) = rec
            .get("toolUseResult")
            .and_then(|r| file_edit(r, at, offset))
        {
            out.push(edit);
        }
    }

    if !injected {
        let typed: Vec<&str> = texts
            .into_iter()
            .map(str::trim)
            .filter(|t| !t.is_empty() && !is_injected(t))
            .collect();
        if !typed.is_empty() {
            out.push(TranscriptItem::UserPrompt {
                at,
                text: truncate_chars(&typed.join("\n\n"), MAX_TEXT_CHARS),
                offset,
            });
        }
    }
}

fn is_injected(text: &str) -> bool {
    INJECTED_PREFIXES.iter().any(|p| text.starts_with(p))
}

/// The text of a tool result's `content`: a string, or text blocks.
fn content_text(content: Option<&Value>) -> String {
    match content {
        Some(Value::String(s)) => s.clone(),
        Some(Value::Array(blocks)) => blocks
            .iter()
            .filter_map(|b| b.get("text").and_then(Value::as_str))
            .collect::<Vec<_>>()
            .join("\n"),
        _ => String::new(),
    }
}

fn assistant(
    rec: &Map<String, Value>,
    at: TimestampMs,
    offset: u64,
    out: &mut Vec<TranscriptItem>,
) {
    let Some(message) = rec.get("message").and_then(Value::as_object) else {
        return;
    };
    match message.get("content") {
        Some(Value::String(s)) => push_text(s, at, offset, out),
        Some(Value::Array(blocks)) => {
            for block in blocks {
                match block.get("type").and_then(Value::as_str) {
                    Some("text") => {
                        if let Some(t) = block.get("text").and_then(Value::as_str) {
                            push_text(t, at, offset, out);
                        }
                    }
                    Some("tool_use") => tool_use(block, at, offset, out),
                    _ => {}
                }
            }
        }
        _ => {}
    }
    if str_at(message, "stop_reason") == Some("end_turn") {
        out.push(TranscriptItem::TurnEnded { at, offset });
    }
}

fn push_text(text: &str, at: TimestampMs, offset: u64, out: &mut Vec<TranscriptItem>) {
    if !text.trim().is_empty() {
        out.push(TranscriptItem::AssistantText {
            at,
            text: truncate_chars(text, MAX_TEXT_CHARS),
            offset,
        });
    }
}

fn tool_use(block: &Value, at: TimestampMs, offset: u64, out: &mut Vec<TranscriptItem>) {
    let (Some(id), Some(tool)) = (
        block.get("id").and_then(Value::as_str),
        block.get("name").and_then(Value::as_str),
    ) else {
        return;
    };
    let input = block.get("input").unwrap_or(&Value::Null);
    out.push(TranscriptItem::ToolUse {
        at,
        call_id: call_id(id),
        tool: truncate_chars(tool, MAX_TOOL_CHARS),
        target: target(tool, input),
        input: (!input.is_null()).then(|| bounded_input(input)),
        offset,
    });
    match tool {
        "TodoWrite" => {
            if let Some(items) = plan(input) {
                out.push(TranscriptItem::PlanUpdated { at, items, offset });
            }
        }
        "AskUserQuestion" => questions(input, at, offset, out),
        _ => {}
    }
}

/// A short description of what a tool call acts on.
fn target(tool: &str, input: &Value) -> String {
    let get = |k: &str| input.get(k).and_then(Value::as_str);
    let found = match tool {
        "Bash" => get("command"),
        "Read" | "Edit" | "MultiEdit" | "Write" => get("file_path"),
        "NotebookEdit" | "NotebookRead" => get("notebook_path"),
        "Grep" | "Glob" => get("pattern"),
        "WebFetch" => get("url"),
        "WebSearch" => get("query"),
        "Task" | "Agent" => get("description"),
        "TodoWrite" => {
            let n = input
                .get("todos")
                .and_then(Value::as_array)
                .map_or(0, Vec::len);
            return format!("{n} items");
        }
        "AskUserQuestion" => input
            .get("questions")
            .and_then(|q| q.get(0))
            .and_then(|q| q.get("question"))
            .and_then(Value::as_str)
            .or_else(|| get("question")),
        _ => None,
    };
    let found = found.or_else(|| {
        [
            "command",
            "file_path",
            "path",
            "pattern",
            "url",
            "query",
            "description",
            "prompt",
        ]
        .into_iter()
        .find_map(get)
    });
    first_line(found.unwrap_or(""), MAX_TARGET_CHARS)
}

/// The tool input with long strings cut; an input still too large becomes a preview.
fn bounded_input(input: &Value) -> Value {
    fn shorten(v: &Value, depth: usize) -> Value {
        match v {
            Value::String(s) => Value::String(truncate_chars(s, MAX_INPUT_STRING_CHARS)),
            _ if depth > 16 => Value::String("…".into()),
            Value::Array(a) => {
                Value::Array(a.iter().take(200).map(|x| shorten(x, depth + 1)).collect())
            }
            Value::Object(o) => Value::Object(
                o.iter()
                    .map(|(k, x)| (k.clone(), shorten(x, depth + 1)))
                    .collect(),
            ),
            other => other.clone(),
        }
    }
    let short = shorten(input, 0);
    let json = serde_json::to_string(&short).unwrap_or_default();
    if json.len() <= MAX_INPUT_JSON_BYTES {
        short
    } else {
        json!({ "truncated": true, "preview": truncate_chars(&json, MAX_INPUT_STRING_CHARS) })
    }
}

fn plan(input: &Value) -> Option<Vec<PlanItem>> {
    let todos = input.get("todos")?.as_array()?;
    Some(
        todos
            .iter()
            .filter_map(|t| {
                let text = t.get("content").and_then(Value::as_str)?;
                let text = truncate_chars(text, MAX_PLAN_TEXT_CHARS);
                let status = match t.get("status").and_then(Value::as_str) {
                    Some("in_progress") => PlanStatus::InProgress,
                    Some("completed") => PlanStatus::Completed,
                    _ => PlanStatus::Pending,
                };
                Some(PlanItem { text, status })
            })
            .take(MAX_PLAN_ITEMS)
            .collect(),
    )
}

fn questions(input: &Value, at: TimestampMs, offset: u64, out: &mut Vec<TranscriptItem>) {
    let one = |q: &Value| -> Option<TranscriptItem> {
        let text = q.get("question").and_then(Value::as_str)?;
        let options = q
            .get("options")
            .and_then(Value::as_array)
            .map(|opts| {
                opts.iter()
                    .filter_map(|o| {
                        o.get("label")
                            .and_then(Value::as_str)
                            .or_else(|| o.as_str())
                    })
                    .take(MAX_OPTIONS)
                    .map(|label| truncate_chars(label, MAX_OPTION_CHARS))
                    .collect()
            })
            .unwrap_or_default();
        Some(TranscriptItem::Question {
            at,
            text: truncate_chars(text, MAX_QUESTION_CHARS),
            options,
            offset,
        })
    };
    match input.get("questions").and_then(Value::as_array) {
        Some(qs) => out.extend(qs.iter().filter_map(one).take(MAX_QUESTIONS)),
        None => out.extend(one(input)),
    }
}

/// A `FileEdit` from an edit tool's `toolUseResult`: counts and diff from `structuredPatch`, or the
/// whole content for a newly created file.
fn file_edit(result: &Value, at: TimestampMs, offset: u64) -> Option<TranscriptItem> {
    let path = truncate_chars(
        result.get("filePath").and_then(Value::as_str)?,
        MAX_PATH_BYTES,
    );
    let hunks = result.get("structuredPatch").and_then(Value::as_array);
    let mut diff = Diff::new(&path);
    let (mut added, mut removed) = (0u32, 0u32);

    match hunks {
        Some(hunks) if !hunks.is_empty() => {
            for h in hunks {
                let n = |k: &str| h.get(k).and_then(Value::as_u64).unwrap_or(0);
                diff.push(&format!(
                    "@@ -{},{} +{},{} @@",
                    n("oldStart"),
                    n("oldLines"),
                    n("newStart"),
                    n("newLines")
                ));
                for line in h
                    .get("lines")
                    .and_then(Value::as_array)
                    .into_iter()
                    .flatten()
                {
                    let Some(line) = line.as_str() else { continue };
                    if line.starts_with('+') {
                        added = added.saturating_add(1);
                    } else if line.starts_with('-') {
                        removed = removed.saturating_add(1);
                    }
                    diff.push(line);
                }
            }
        }
        _ if result.get("type").and_then(Value::as_str) == Some("create") => {
            let content = result.get("content").and_then(Value::as_str)?;
            let n = content.lines().count();
            added = u32::try_from(n).unwrap_or(u32::MAX);
            diff.push(&format!("@@ -0,0 +1,{n} @@"));
            for line in content.lines() {
                diff.push(&format!("+{line}"));
            }
        }
        _ => return None,
    }
    Some(TranscriptItem::FileEdit {
        at,
        path,
        added,
        removed,
        diff: Some(diff.finish()),
        offset,
    })
}

/// A unified diff capped at [`MAX_DIFF_BYTES`].
struct Diff {
    text: String,
    full: bool,
}

impl Diff {
    fn new(path: &str) -> Self {
        Self {
            text: format!("--- {path}\n+++ {path}\n"),
            full: false,
        }
    }

    fn push(&mut self, line: &str) {
        if self.full {
            return;
        }
        if self.text.len() + line.len() + 1 > MAX_DIFF_BYTES {
            self.text.push_str("… (diff truncated)\n");
            self.full = true;
            return;
        }
        self.text.push_str(line);
        self.text.push('\n');
    }

    fn finish(self) -> String {
        self.text
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn items(line: &str) -> Vec<TranscriptItem> {
        parse_line(line.as_bytes(), 7).expect("parses").items
    }

    #[test]
    fn injected_user_text_is_not_a_prompt() {
        for text in [
            "<command-name>/clear</command-name>",
            "<local-command-stdout></local-command-stdout>",
            "<system-reminder>x</system-reminder>",
            "[Request interrupted by user]",
        ] {
            let line = json!({"type": "user", "message": {"role": "user", "content": text}});
            assert!(items(&line.to_string()).is_empty(), "{text}");
        }
        let meta = json!({"type": "user", "isMeta": true, "message": {"content": "hello"}});
        assert!(items(&meta.to_string()).is_empty());
    }

    #[test]
    fn typed_text_beside_a_reminder_is_kept() {
        let line = json!({"type": "user", "timestamp": "1970-01-01T00:00:01Z", "message": {"content": [
            {"type": "text", "text": "<system-reminder>ignore</system-reminder>"},
            {"type": "text", "text": "  fix the bug  "}
        ]}});
        assert_eq!(
            items(&line.to_string()),
            vec![TranscriptItem::UserPrompt {
                at: 1000,
                text: "fix the bug".into(),
                offset: 7
            }]
        );
    }

    #[test]
    fn wrong_shapes_give_no_items() {
        for line in [
            r#"{"type":"assistant","message":5}"#,
            r#"{"type":"assistant","message":{"content":[1,{"type":"tool_use"}]}}"#,
            r#"{"type":"user","message":{"content":[{"type":"tool_result","tool_use_id":3}]}}"#,
            r#"{"type":["user"]}"#,
            r#"{}"#,
        ] {
            assert!(items(line).is_empty(), "{line}");
        }
        assert!(matches!(
            parse_line(b"[1,2]", 0),
            Err(SkipReason::Malformed(_))
        ));
        assert!(matches!(
            parse_line(b"{\"a\":", 0),
            Err(SkipReason::Malformed(_))
        ));
        assert_eq!(
            parse_line(b"{\"a\":\"\xff\"}", 0),
            Err(SkipReason::InvalidUtf8)
        );
    }

    #[test]
    fn large_inputs_are_bounded() {
        let big = "x".repeat(100_000);
        let line = json!({"type": "assistant", "message": {"content": [
            {"type": "tool_use", "id": "t1", "name": "Write", "input": {"file_path": "/a", "content": big}}
        ]}});
        let [
            TranscriptItem::ToolUse {
                input: Some(input),
                target,
                ..
            },
        ] = &items(&line.to_string())[..]
        else {
            panic!("expected one tool use");
        };
        assert_eq!(target, "/a");
        assert!(input.to_string().len() < MAX_INPUT_JSON_BYTES);
    }

    #[test]
    fn an_input_too_large_after_cutting_becomes_a_preview() {
        let keys: Map<String, Value> = (0..100)
            .map(|i| (format!("k{i}"), Value::String("y".repeat(1000))))
            .collect();
        let line = json!({"type": "assistant", "message": {"content": [
            {"type": "tool_use", "id": "t1", "name": "Custom", "input": Value::Object(keys)}
        ]}});
        let [
            TranscriptItem::ToolUse {
                input: Some(input), ..
            },
        ] = &items(&line.to_string())[..]
        else {
            panic!("expected one tool use");
        };
        assert_eq!(input["truncated"], json!(true));
        let preview = input["preview"].as_str().expect("preview");
        assert_eq!(preview.chars().count(), MAX_INPUT_STRING_CHARS + 1);
    }

    #[test]
    fn every_payload_is_capped() {
        // Each value just over its cap, so the test stays small.
        let long = "z".repeat(MAX_QUESTION_CHARS + 10);
        let label = "l".repeat(MAX_OPTION_CHARS + 10);
        let todos: Vec<Value> = (0..MAX_PLAN_ITEMS + 10)
            .map(|_| json!({"content": long, "status": "pending"}))
            .collect();
        let options: Vec<Value> = (0..MAX_OPTIONS + 10)
            .map(|_| json!({"label": label}))
            .collect();
        let questions: Vec<Value> = (0..MAX_QUESTIONS + 10)
            .map(|_| json!({"question": long, "options": options}))
            .collect();
        let line = json!({"type": "assistant", "message": {"content": [
            {"type": "tool_use", "id": long, "name": long, "input": {}},
            {"type": "tool_use", "id": "p", "name": "TodoWrite", "input": {"todos": todos}},
            {"type": "tool_use", "id": "q", "name": "AskUserQuestion", "input": {"questions": questions}},
        ]}});
        let got = items(&line.to_string());
        let TranscriptItem::ToolUse { call_id, tool, .. } = &got[0] else {
            panic!("tool use first");
        };
        assert!(call_id.chars().count() <= MAX_ID_BYTES + 1);
        assert!(tool.chars().count() <= MAX_TOOL_CHARS + 1);
        let TranscriptItem::PlanUpdated { items: plan, .. } = &got[2] else {
            panic!("plan third");
        };
        assert_eq!(plan.len(), MAX_PLAN_ITEMS);
        assert!(
            plan.iter()
                .all(|p| p.text.chars().count() <= MAX_PLAN_TEXT_CHARS + 1)
        );
        let asked: Vec<_> = got
            .iter()
            .filter_map(|i| match i {
                TranscriptItem::Question { text, options, .. } => Some((text, options)),
                _ => None,
            })
            .collect();
        assert_eq!(asked.len(), MAX_QUESTIONS);
        for (text, options) in asked {
            assert!(text.chars().count() <= MAX_QUESTION_CHARS + 1);
            assert_eq!(options.len(), MAX_OPTIONS);
            assert!(
                options
                    .iter()
                    .all(|o| o.chars().count() <= MAX_OPTION_CHARS + 1)
            );
        }

        let result = json!({"type": "user",
            "message": {"content": [{"type": "tool_result", "tool_use_id": long, "content": "ok"}]},
            "toolUseResult": {"filePath": "p".repeat(10_000), "structuredPatch": [
                {"oldStart": 1, "oldLines": 0, "newStart": 1, "newLines": 1, "lines": ["+a"]}]}});
        let got = items(&result.to_string());
        let (
            TranscriptItem::ToolResult { call_id: rid, .. },
            TranscriptItem::FileEdit { path, .. },
        ) = (&got[0], &got[1])
        else {
            panic!("result then edit");
        };
        assert_eq!(rid, call_id, "cut ids still pair");
        assert!(path.chars().count() <= MAX_PATH_BYTES + 1);
    }

    #[test]
    fn oversized_facts_are_dropped_or_cut() {
        let long = "f".repeat(100_000);
        let line = json!({"type": "summary", "sessionId": long, "cwd": long, "gitBranch": long,
                          "summary": format!("  a   short\n start {long}")});
        let facts = parse_line(line.to_string().as_bytes(), 0)
            .expect("parses")
            .facts;
        assert_eq!(
            (facts.session_id, facts.cwd, facts.branch),
            (None, None, None)
        );
        let summary = facts.summary.expect("summary");
        assert!(summary.starts_with("a short start ff"));
        assert_eq!(summary.chars().count(), MAX_TITLE_CHARS + 1);
    }

    #[test]
    fn created_file_counts_its_lines() {
        let line = json!({"type": "user",
            "message": {"content": [{"type": "tool_result", "tool_use_id": "t1", "content": "ok"}]},
            "toolUseResult": {"type": "create", "filePath": "/a.txt", "content": "one\ntwo\n", "structuredPatch": []}});
        let got = items(&line.to_string());
        assert!(matches!(
            &got[1],
            TranscriptItem::FileEdit { added: 2, removed: 0, diff: Some(d), .. } if d.ends_with("+one\n+two\n")
        ));
    }
}
