// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Engine } from "./Engine.ts";

/**
 * One agent CLI's account on a machine, as the CLI's own status command reported it
 * (`GET /v1/machines/{id}/agents`).
 */
export type AgentAccount = { 
/**
 * The CLI.
 */
engine: Engine, 
/**
 * Whether the CLI is on the machine's `PATH`.
 */
installed: boolean, 
/**
 * Whether the CLI says it is signed in. Absent when it could not tell: it is not installed,
 * it is too old to have a status command, it did not answer in time, or it printed
 * something PitCrew does not understand.
 */
signed_in?: boolean, 
/**
 * The account, as the CLI printed it (an e-mail address, `ChatGPT`, `API key`, a count of
 * providers); never a key or a token. At most 120 characters.
 */
account?: string, 
/**
 * Why `signed_in` is absent, for people.
 */
detail?: string, };
