// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReferenceTarget } from "./ReferenceTarget.ts";

/**
 * Something an answer cites that the hub knows, which the panel links to.
 */
export type AnswerReference = { 
/**
 * The reference exactly as the answer has it, e.g. `ses_01JB…` or `PAP-4`.
 */
text: string, 
/**
 * What it points to.
 */
target: ReferenceTarget, 
/**
 * A short name for it: a session's title, a task's key and title, a workstream's name.
 */
label: string, };
