// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReferenceTarget } from "./ReferenceTarget.ts";
import type { TaskId } from "./TaskId.ts";
import type { TaskKey } from "./TaskKey.ts";
import type { TaskStatus } from "./TaskStatus.ts";

/**
 * An action an answer suggests. It does nothing by itself: the panel shows it, and only the
 * person's click acts, as the person, through the usual route.
 */
export type AnswerSuggestion = { "kind": "move_task", 
/**
 * The task.
 */
task: TaskId, 
/**
 * Its key.
 */
key: TaskKey, 
/**
 * Where to.
 */
to: TaskStatus, 
/**
 * What the button says, e.g. "Move PAP-4 to review".
 */
label: string, } | { "kind": "open", 
/**
 * The page.
 */
target: ReferenceTarget, 
/**
 * What the button says.
 */
label: string, };
