// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What an answer took, from its transcript.
 */
export type AnswerUsage = { 
/**
 * From the question to the answer's end, in milliseconds.
 */
duration_ms: number, 
/**
 * The tools its CLI ran meanwhile (the `pitcrew` reads among them).
 */
tool_runs: number, 
/**
 * The answer's size, in bytes.
 */
answer_bytes: number, };
