// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemberId } from "./MemberId.ts";

/**
 * An answer to an ask.
 */
export type Answer = { 
/**
 * Who answered. For decisions and approvals, always a person.
 */
by: MemberId, 
/**
 * The chosen option's index, if the ask offered options.
 */
option?: number, 
/**
 * Free-text answer.
 */
text?: string, 
/**
 * When.
 */
at: number, };
