// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorCode } from "./ErrorCode.ts";

/**
 * The error body of every failed request.
 */
export type ApiError = { 
/**
 * Code.
 */
code: ErrorCode, 
/**
 * A sentence for people.
 */
message: string, };
