// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Answer } from "./Answer.ts";
import type { AskId } from "./AskId.ts";
import type { AskKind } from "./AskKind.ts";
import type { AskState } from "./AskState.ts";
import type { MemberId } from "./MemberId.ts";
import type { Receipt } from "./Receipt.ts";
import type { SessionId } from "./SessionId.ts";
import type { TaskId } from "./TaskId.ts";

/**
 * Something that needs a specific member's answer. Asks are what the Inbox lists.
 */
export type Ask = { 
/**
 * Id.
 */
id: AskId, 
/**
 * Kind.
 */
kind: AskKind, 
/**
 * Who is asking (an agent, the back office's member, or a person).
 */
from: MemberId, 
/**
 * Who must answer.
 */
to: MemberId, 
/**
 * Related task.
 */
task?: TaskId, 
/**
 * Related session.
 */
session?: SessionId, 
/**
 * One-line title.
 */
title: string, 
/**
 * Context.
 */
body: string, 
/**
 * Offered options, in order.
 */
options: Array<string>, 
/**
 * Evidence.
 */
receipts: Array<Receipt>, 
/**
 * Lifecycle.
 */
state: AskState, 
/**
 * The answer, once given.
 */
answer?: Answer, 
/**
 * When it was raised.
 */
created: number, };
