// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An ask: something that needs a specific member's answer.
 */
export type AskId = string;
