// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lifecycle of an ask.
 */
export type AskState = "open" | "answered" | "withdrawn";
