// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A person's avatar preferences.
 */
export type Avatar = { 
/**
 * One to four visible Unicode code points.
 */
initials: string, 
/**
 * A six-digit hexadecimal RGB colour.
 */
colour: string, };
