// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Back-office acceptance budget.
 */
export type BackOfficeCaps = { 
/**
 * Zero disables automatic acceptance; at most 100.
 */
max_auto_accept_per_hour: number, };
