// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectId } from "./ProjectId.ts";
import type { SessionId } from "./SessionId.ts";
import type { WorkstreamId } from "./WorkstreamId.ts";

/**
 * What a block groups: one session's events, or, for events outside any active session, one
 * workstream's (or, for tasks without a workstream, one project's).
 */
export type BlockKey = { "kind": "session", "id": SessionId } | { "kind": "workstream", "id": WorkstreamId } | { "kind": "project", "id": ProjectId };
