// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlockKey } from "./BlockKey.ts";
import type { Counts } from "./Counts.ts";
import type { EventId } from "./EventId.ts";
import type { Fact } from "./Fact.ts";
import type { FileTouch } from "./FileTouch.ts";
import type { MemberId } from "./MemberId.ts";
import type { ProjectId } from "./ProjectId.ts";
import type { Receipt } from "./Receipt.ts";
import type { SessionId } from "./SessionId.ts";
import type { TaskId } from "./TaskId.ts";
import type { WorkstreamId } from "./WorkstreamId.ts";

/**
 * A burst of work: events of one key with no pause longer than the gap.
 */
export type Block = { 
/**
 * The first event's id. It is stable: rebuilding from the same events gives the same id.
 */
id: EventId, 
/**
 * The last event's id. With `id`, the range of the log the block covers.
 */
last: EventId, 
/**
 * What the block groups.
 */
key: BlockKey, 
/**
 * Time of the earliest event.
 */
start: number, 
/**
 * Time of the latest event.
 */
end: number, 
/**
 * The session, for a session's block.
 */
session?: SessionId, 
/**
 * The workstream the work belongs to, if known.
 */
workstream?: WorkstreamId, 
/**
 * The project the work belongs to, if known.
 */
project?: ProjectId, 
/**
 * Tasks the work touched, in order of first mention (capped).
 */
tasks: Array<TaskId>, 
/**
 * The agent doing the work: the session's agent, or the author of the first tool run, edit
 * or turn.
 */
agent?: MemberId, 
/**
 * Distinct authors of the block's events, in order of first appearance (capped).
 */
actors: Array<MemberId>, 
/**
 * Counts.
 */
counts: Counts, 
/**
 * Files edited, in order of first edit (capped).
 */
files: Array<FileTouch>, 
/**
 * Edits to files beyond the cap.
 */
files_omitted: number, 
/**
 * Notable facts, in order of first occurrence (capped).
 */
facts: Array<Fact>, 
/**
 * Facts beyond the cap.
 */
facts_omitted: number, 
/**
 * Receipts for the tool runs: the first ones.
 */
tool_receipts: Array<Receipt>, 
/**
 * Receipts for the turns: the first ones.
 */
turn_receipts: Array<Receipt>, };
