// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecapBlock } from "./RecapBlock.ts";

/**
 * `GET /v1/recaps/blocks`: a page of blocks, newest first.
 *
 * Page backwards by passing the last block's `id` as `before`. Only `at_start` ends paging.
 */
export type BlocksPage = { 
/**
 * The blocks, newest first (by block id).
 */
blocks: Array<RecapBlock>, 
/**
 * True when no older matching block exists.
 */
at_start: boolean, };
