// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BoardProposal } from "./BoardProposal.ts";
import type { DraftCost } from "./DraftCost.ts";
import type { DraftId } from "./DraftId.ts";
import type { DraftState } from "./DraftState.ts";
import type { DraftedTask } from "./DraftedTask.ts";
import type { Engine } from "./Engine.ts";
import type { MemberId } from "./MemberId.ts";
import type { SessionId } from "./SessionId.ts";
import type { WorkstreamId } from "./WorkstreamId.ts";

/**
 * A board draft, as the hub keeps it (`GET /v1/board-drafts`).
 */
export type BoardDraft = { 
/**
 * Id.
 */
id: DraftId, 
/**
 * The workstream it drafts.
 */
workstream: WorkstreamId, 
/**
 * The agent drafting it.
 */
agent: MemberId, 
/**
 * The CLI it runs in.
 */
engine: Engine, 
/**
 * The session the agent runs in.
 */
session: SessionId, 
/**
 * The person who asked for it.
 */
by: MemberId, 
/**
 * The prompt's name and version.
 */
prompt: string, 
/**
 * What was sent, and the estimate the person confirmed.
 */
cost: DraftCost, 
/**
 * When it started.
 */
started: number, 
/**
 * Where it is.
 */
state: DraftState, 
/**
 * The agent's proposal, once it has made one.
 */
proposal?: BoardProposal, 
/**
 * When the proposal came.
 */
proposed?: number, 
/**
 * When the person reviewed it.
 */
reviewed?: number, 
/**
 * The proposed tasks the person accepted, and the tasks they became.
 */
accepted: Array<DraftedTask>, 
/**
 * The proposed tasks the person rejected.
 */
rejected: Array<number>, };
