// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProposedTask } from "./ProposedTask.ts";

/**
 * What the drafting agent proposes (`POST /v1/board-drafts/{id}/proposal`).
 */
export type BoardProposal = { 
/**
 * The tasks, in the order the agent gives them; a review names them by their index here.
 */
tasks: Array<ProposedTask>, 
/**
 * Anything else the agent wants the person to know.
 */
note?: string, };
