// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who wrote the brief currently in force.
 */
export type BriefSource = "person" | "back_office";
