// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BriefProposal } from "./BriefProposal.ts";
import type { BriefSource } from "./BriefSource.ts";
import type { BriefTarget } from "./BriefTarget.ts";
import type { Receipt } from "./Receipt.ts";

/**
 * The "Where it stands" text of a project or workstream, as currently in force.
 */
export type Brief = { 
/**
 * Which brief.
 */
target: BriefTarget, 
/**
 * The text.
 */
text: string, 
/**
 * The next step, if stated.
 */
next?: string, 
/**
 * Pinned by a person; the back office may then only propose changes.
 */
pinned: boolean, 
/**
 * Who wrote the version in force.
 */
source: BriefSource, 
/**
 * When it was last updated.
 */
updated: number, 
/**
 * Evidence behind it.
 */
receipts: Array<Receipt>, 
/**
 * The pending proposal, present exactly when there is one: the newest `brief_proposed` for
 * the target, newer than the `brief_accepted` that put this brief in force.
 */
proposal?: BriefProposal, };
