// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectId } from "./ProjectId.ts";
import type { WorkstreamId } from "./WorkstreamId.ts";

/**
 * Which brief ("Where it stands") something is about.
 */
export type BriefTarget = { "kind": "project", "id": ProjectId } | { "kind": "workstream", "id": WorkstreamId };
