// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Receipt } from "./Receipt.ts";

/**
 * A new "Where it stands" the back office proposed, waiting for a person to accept it or keep
 * the current one (see [`Brief::proposal`]).
 */
export type BriefProposal = { 
/**
 * Proposed text.
 */
text: string, 
/**
 * Proposed next step, if any.
 */
next?: string, 
/**
 * Evidence for every claim.
 */
receipts: Array<Receipt>, 
/**
 * When it was proposed: the time of its `brief_proposed`.
 */
at: number, };
