// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemberId } from "./MemberId.ts";
import type { TokenScope } from "./TokenScope.ts";

/**
 * Who is calling, as established by the API layer (stream H) from the bearer token.
 *
 * Domain crates never parse tokens. Their `routes()` read the caller from the request's
 * extensions (`axum::Extension<Caller>`), which the API layer inserts after authentication, and
 * stamp events with `author = member` and `on_behalf_of`.
 */
export type Caller = { 
/**
 * The member the token belongs to: a person (device token) or an agent (agent token).
 */
member: MemberId, 
/**
 * The token's scope.
 */
scope: TokenScope, 
/**
 * For an agent, its owner.
 */
on_behalf_of?: MemberId, };
