// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a runner can do on its machine.
 */
export type Capability = "tmux" | "pty" | "slurm" | "watch" | "scan";
