// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A kind of check a command runs. The order is the strength used for command chains.
 */
export type Check = "tests" | "lint" | "build";
