// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why an issue is closed (GitHub's `state_reason`).
 */
export type CloseReason = "completed" | "not_planned";
