// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A command sent from a hub to a runner. It doubles as the idempotency key.
 */
export type CommandId = string;
