// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue.ts";

/**
 * The outcome of a command.
 */
export type CommandOutcome = { "status": "ok", 
/**
 * Detail.
 */
detail?: JsonValue, } | { "status": "rejected", 
/**
 * Why.
 */
reason: string, } | { "status": "failed", 
/**
 * What went wrong.
 */
error: string, };
