// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An Orchestrator conversation: a person's questions and the answers to them.
 */
export type ConversationId = string;
