// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConversationId } from "./ConversationId.ts";
import type { Engine } from "./Engine.ts";
import type { MemberId } from "./MemberId.ts";
import type { OrchestratorTurn } from "./OrchestratorTurn.ts";
import type { SessionId } from "./SessionId.ts";

/**
 * A person's questions and the answers to them, in one agent CLI.
 */
export type Conversation = { 
/**
 * Its id.
 */
id: ConversationId, 
/**
 * Its CLI.
 */
engine: Engine, 
/**
 * The agent its sessions run as.
 */
agent: MemberId, 
/**
 * When it started.
 */
started: number, 
/**
 * The session that answers it, while that lives.
 */
session?: SessionId, 
/**
 * Its questions and answers, oldest first.
 */
turns: Array<OrchestratorTurn>, };
