// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Counts over all of a block's events. They are never capped.
 */
export type Counts = { 
/**
 * Events in the block.
 */
events: number, 
/**
 * Tool runs.
 */
tools_run: number, 
/**
 * Tool runs that failed.
 */
tools_failed: number, 
/**
 * File edits.
 */
file_edits: number, 
/**
 * Lines added over all edits.
 */
lines_added: number, 
/**
 * Lines removed over all edits.
 */
lines_removed: number, 
/**
 * Turns ended.
 */
turns: number, 
/**
 * Asks raised.
 */
asks_raised: number, 
/**
 * Asks answered.
 */
asks_answered: number, 
/**
 * Task moves.
 */
task_moves: number, 
/**
 * Comments posted.
 */
comments: number, };
