// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CredentialSource } from "./CredentialSource.ts";

/**
 * What a route may say about a credential: never the credential itself.
 */
export type CredentialInfo = { 
/**
 * Where it comes from.
 */
source: CredentialSource, 
/**
 * Whether a secret is kept (always `false` for `gh_cli`).
 */
stored: boolean, };
