// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A calendar date without a time zone, written `YYYY-MM-DD`.
 */
export type Date = string;
