// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Date } from "./Date.ts";
import type { EventId } from "./EventId.ts";
import type { Summary } from "./Summary.ts";
import type { WorkstreamId } from "./WorkstreamId.ts";

/**
 * The paragraph for one workstream's day, with the blocks it covers.
 */
export type DayRecap = { 
/**
 * The workstream; `None` for blocks not linked to one.
 */
workstream?: WorkstreamId, 
/**
 * The day.
 */
date: Date, 
/**
 * Ids of the blocks covered, in order.
 */
blocks: Array<EventId>, 
/**
 * The paragraph.
 */
summary: Summary, };
