// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DayRecap } from "./DayRecap.ts";

/**
 * `GET /v1/recaps/days`: a page of day paragraphs, newest day first.
 *
 * Page backwards by passing the last entry's `date` as `before`. Only `at_start` ends paging.
 */
export type DaysPage = { 
/**
 * The paragraphs: newest date first; within a date, the one without a workstream first,
 * then by workstream id.
 */
days: Array<DayRecap>, 
/**
 * True when no older day with matching activity exists.
 */
at_start: boolean, };
