// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DispatchId } from "./DispatchId.ts";
import type { DispatchOutcome } from "./DispatchOutcome.ts";
import type { MemberId } from "./MemberId.ts";
import type { SessionId } from "./SessionId.ts";
import type { TaskId } from "./TaskId.ts";

/**
 * One attempt at a task by one agent.
 */
export type Dispatch = { 
/**
 * Id.
 */
id: DispatchId, 
/**
 * The task.
 */
task: TaskId, 
/**
 * The agent.
 */
agent: MemberId, 
/**
 * The session running it, once started.
 */
session?: SessionId, 
/**
 * The brief the agent was given.
 */
brief: string, 
/**
 * Start time.
 */
started: number, 
/**
 * End time.
 */
ended?: number, 
/**
 * Outcome.
 */
outcome?: DispatchOutcome, 
/**
 * The agent's closing summary.
 */
summary?: string, };
