// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A dispatch: one attempt at a task by one agent.
 */
export type DispatchId = string;
