// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A board draft: one agent drafting a workstream's board from its history.
 */
export type DraftId = string;
