// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UsageEstimate } from "./UsageEstimate.ts";

/**
 * What a draft sends to its agent, and what that is likely to cost.
 */
export type DraftCost = { 
/**
 * The workstream's sessions the summary covers.
 */
sessions: number, 
/**
 * The workstream's sessions left out by the summary's bounds: the least recently active.
 */
sessions_left_out: number, 
/**
 * The workstream's tasks the summary lists, so the agent does not propose them again.
 */
tasks: number, 
/**
 * The summary's size in bytes (UTF-8).
 */
summary_bytes: number, 
/**
 * The whole prompt's size in bytes: the versioned template with the summary in it.
 */
prompt_bytes: number, 
/**
 * Strings the summary replaced because they looked like secrets, e-mail addresses or a
 * person's home folder.
 */
redacted: number, 
/**
 * The agent's likely usage.
 */
estimate: UsageEstimate, };
