// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a draft is.
 */
export type DraftState = "running" | "proposed" | "reviewed" | "ended";
