// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DraftCost } from "./DraftCost.ts";
import type { WorkstreamId } from "./WorkstreamId.ts";

/**
 * `GET /v1/workstreams/{id}/board-draft`: what a draft of the workstream would send, before
 * anything is.
 */
export type DraftPreview = { 
/**
 * The workstream.
 */
workstream: WorkstreamId, 
/**
 * The prompt's name and version, e.g. `draft-board/v1`.
 */
prompt: string, 
/**
 * The sizes and the estimate.
 */
cost: DraftCost, 
/**
 * The summary, exactly as the agent would read it.
 */
summary: string, 
/**
 * The SHA-256 of the whole prompt, as lowercase hex. A start names it: if the workstream has
 * changed since, the prompt would differ, and the start is refused (`409`).
 */
digest: string, };
