// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `POST /v1/board-drafts/{id}/review`: which proposed tasks to create. Every other one is
 * rejected; an empty list rejects the whole proposal.
 */
export type DraftReview = { 
/**
 * Indexes into [`BoardProposal::tasks`].
 */
accept: Array<number>, };
