// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskId } from "./TaskId.ts";

/**
 * A proposed task the person accepted, and the task it became.
 */
export type DraftedTask = { 
/**
 * Its index in [`BoardProposal::tasks`].
 */
item: number, 
/**
 * The task created.
 */
task: TaskId, };
