// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BoardDraft } from "./BoardDraft.ts";
import type { Task } from "./Task.ts";

/**
 * The answer to a review: the draft as it is now, and the tasks it created.
 */
export type DraftReviewed = { 
/**
 * The draft, reviewed.
 */
draft: BoardDraft, 
/**
 * The tasks created, in the order of the proposal.
 */
tasks: Array<Task>, };
