// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Engine } from "./Engine.ts";

/**
 * Sessions found for one engine.
 */
export type EngineCount = { 
/**
 * The CLI.
 */
engine: Engine, 
/**
 * Sessions found.
 */
count: number, };
