// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Engine } from "./Engine.ts";

/**
 * Whether an agent CLI can answer questions.
 */
export type EngineStatus = { 
/**
 * The CLI.
 */
engine: Engine, 
/**
 * Whether it is on the `PATH` of the hub's own machine, where questions run.
 */
installed: boolean, };
