// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Machine-readable error codes.
 */
export type ErrorCode = "unauthorized" | "forbidden" | "not_found" | "conflict" | "invalid" | "unavailable" | "internal";
