// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventBody } from "./EventBody.ts";
import type { EventId } from "./EventId.ts";
import type { MemberId } from "./MemberId.ts";
import type { WorkspaceId } from "./WorkspaceId.ts";

/**
 * One entry in the log.
 */
export type Event = { 
/**
 * Id; sorts by creation time.
 */
id: EventId, 
/**
 * When it happened.
 */
at: number, 
/**
 * The workspace.
 */
workspace: WorkspaceId, 
/**
 * Who did it. Stamped by the hub.
 */
author: MemberId, 
/**
 * For an agent's events, the person it acts for.
 */
on_behalf_of?: MemberId, 
/**
 * What happened.
 */
body: EventBody, };
