// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Answer } from "./Answer.ts";
import type { Ask } from "./Ask.ts";
import type { AskId } from "./AskId.ts";
import type { BriefTarget } from "./BriefTarget.ts";
import type { Dispatch } from "./Dispatch.ts";
import type { DispatchId } from "./DispatchId.ts";
import type { DispatchOutcome } from "./DispatchOutcome.ts";
import type { ExternalRef } from "./ExternalRef.ts";
import type { Health } from "./Health.ts";
import type { LinkBasis } from "./LinkBasis.ts";
import type { Liveness } from "./Liveness.ts";
import type { Machine } from "./Machine.ts";
import type { MachineId } from "./MachineId.ts";
import type { Member } from "./Member.ts";
import type { MemberId } from "./MemberId.ts";
import type { Mover } from "./Mover.ts";
import type { Persona } from "./Persona.ts";
import type { Project } from "./Project.ts";
import type { Receipt } from "./Receipt.ts";
import type { SafetySettings } from "./SafetySettings.ts";
import type { Session } from "./Session.ts";
import type { SessionId } from "./SessionId.ts";
import type { SessionState } from "./SessionState.ts";
import type { Subtask } from "./Subtask.ts";
import type { Task } from "./Task.ts";
import type { TaskId } from "./TaskId.ts";
import type { TaskPatch } from "./TaskPatch.ts";
import type { TaskStatus } from "./TaskStatus.ts";
import type { Team } from "./Team.ts";
import type { Workstream } from "./Workstream.ts";
import type { WorkstreamId } from "./WorkstreamId.ts";
import type { WorkstreamStatus } from "./WorkstreamStatus.ts";
import type { WriteProposal } from "./WriteProposal.ts";
import type { WriteResult } from "./WriteResult.ts";

/**
 * What happened. On the wire: `{"type": "task_moved", "data": {…}}`.
 */
export type EventBody = { "type": "safety_changed", "data": { 
/**
 * Validated preferences.
 */
settings: SafetySettings, } } | { "type": "cursor_moved", "data": { 
/**
 * `workspace`, `project:<id>` or `workstream:<id>`.
 */
scope: string, 
/**
 * Last seen log revision.
 */
rev: number, } } | { "type": "machine_added", "data": { 
/**
 * The machine.
 */
machine: Machine, } } | { "type": "member_added", "data": { 
/**
 * The member.
 */
member: Member, } } | { "type": "persona_saved", "data": { 
/**
 * The persona.
 */
persona: Persona, } } | { "type": "team_saved", "data": { 
/**
 * The team.
 */
team: Team, } } | { "type": "machine_liveness", "data": { 
/**
 * The machine.
 */
machine: MachineId, 
/**
 * New liveness.
 */
liveness: Liveness, } } | { "type": "session_discovered", "data": { 
/**
 * The session as first seen.
 */
session: Session, } } | { "type": "session_state_changed", "data": { 
/**
 * The session.
 */
session: SessionId, 
/**
 * Previous state.
 */
from: SessionState, 
/**
 * New state.
 */
to: SessionState, 
/**
 * A one-line status, if the runner has one.
 */
status_line?: string, } } | { "type": "turn_ended", "data": { 
/**
 * The session.
 */
session: SessionId, 
/**
 * Where the turn is in the transcript.
 */
receipt: Receipt, } } | { "type": "tool_ran", "data": { 
/**
 * The session.
 */
session: SessionId, 
/**
 * The tool, e.g. `Bash`.
 */
tool: string, 
/**
 * A short target, e.g. the command or file.
 */
target: string, 
/**
 * A short outcome, e.g. "212 of 240 passed".
 */
outcome: string, 
/**
 * Whether it failed.
 */
failed: boolean, 
/**
 * Where it is in the transcript.
 */
receipt: Receipt, } } | { "type": "file_edited", "data": { 
/**
 * The session.
 */
session: SessionId, 
/**
 * Path, relative to the session's working directory where possible.
 */
path: string, 
/**
 * Lines added.
 */
added: number, 
/**
 * Lines removed.
 */
removed: number, 
/**
 * Where the edit is in the transcript.
 */
receipt?: Receipt, } } | { "type": "session_updated", "data": { 
/**
 * The session.
 */
session: SessionId, 
/**
 * New title, if it changed.
 */
title?: string, 
/**
 * New git branch, if it changed.
 */
branch?: string, } } | { "type": "session_linked", "data": { 
/**
 * The session.
 */
session: SessionId, 
/**
 * The workstream.
 */
workstream?: WorkstreamId, 
/**
 * The task.
 */
task?: TaskId, 
/**
 * Why.
 */
basis: LinkBasis, } } | { "type": "session_ended", "data": { 
/**
 * The session.
 */
session: SessionId, } } | { "type": "project_created", "data": { 
/**
 * The project.
 */
project: Project, } } | { "type": "workstream_created", "data": { 
/**
 * The workstream.
 */
workstream: Workstream, } } | { "type": "workstream_changed", "data": { 
/**
 * The workstream.
 */
workstream: WorkstreamId, 
/**
 * New status.
 */
status: WorkstreamStatus, 
/**
 * New health.
 */
health: Health, } } | { "type": "workstream_linked", "data": { 
/**
 * The workstream.
 */
workstream: WorkstreamId, 
/**
 * The full new list.
 */
external: Array<ExternalRef>, } } | { "type": "task_created", "data": { 
/**
 * The task.
 */
task: Task, } } | { "type": "task_moved", "data": { 
/**
 * The task.
 */
task: TaskId, 
/**
 * Previous status.
 */
from: TaskStatus, 
/**
 * New status.
 */
to: TaskStatus, 
/**
 * Who moved it.
 */
mover: Mover, } } | { "type": "task_assigned", "data": { 
/**
 * The task.
 */
task: TaskId, 
/**
 * The new assignee.
 */
assignee?: MemberId, } } | { "type": "task_updated", "data": { 
/**
 * The task.
 */
task: TaskId, 
/**
 * Only the fields that changed, with their new values.
 */
patch: TaskPatch, } } | { "type": "subtasks_replaced", "data": { 
/**
 * The task.
 */
task: TaskId, 
/**
 * The full new list.
 */
subtasks: Array<Subtask>, } } | { "type": "dispatch_started", "data": { 
/**
 * The dispatch.
 */
dispatch: Dispatch, } } | { "type": "dispatch_finished", "data": { 
/**
 * The dispatch.
 */
dispatch: DispatchId, 
/**
 * Outcome.
 */
outcome: DispatchOutcome, 
/**
 * The agent's closing summary.
 */
summary?: string, } } | { "type": "ask_raised", "data": { 
/**
 * The ask.
 */
ask: Ask, } } | { "type": "ask_answered", "data": { 
/**
 * The ask.
 */
ask: AskId, 
/**
 * The answer.
 */
answer: Answer, } } | { "type": "comment_posted", "data": { 
/**
 * On this task.
 */
task?: TaskId, 
/**
 * Or on this workstream.
 */
workstream?: WorkstreamId, 
/**
 * Text (markdown).
 */
text: string, 
/**
 * Mentioned members. A mention gives an agent one turn.
 */
mentions: Array<MemberId>, } } | { "type": "brief_proposed", "data": { 
/**
 * Which brief.
 */
target: BriefTarget, 
/**
 * Proposed text.
 */
text: string, 
/**
 * Proposed next step, if any.
 */
next?: string, 
/**
 * Evidence for every claim.
 */
receipts: Array<Receipt>, } } | { "type": "brief_accepted", "data": { 
/**
 * Which brief.
 */
target: BriefTarget, 
/**
 * The text now in force.
 */
text: string, 
/**
 * The next step now in force, if any.
 */
next?: string, 
/**
 * Whether a person pinned it. Pinned briefs only get proposals.
 */
pinned: boolean, 
/**
 * Evidence, copied from the proposal it accepts; empty for a person's own text.
 */
receipts?: Array<Receipt>, } } | { "type": "decision_recorded", "data": { 
/**
 * Workstream it belongs to.
 */
workstream?: WorkstreamId, 
/**
 * The decision.
 */
text: string, 
/**
 * Why.
 */
why?: string, 
/**
 * Evidence.
 */
receipts: Array<Receipt>, } } | { "type": "write_proposed", "data": { 
/**
 * Exactly what will be sent. Boxed: it is the largest body by far.
 */
write: WriteProposal, } } | { "type": "write_started", "data": { 
/**
 * The write's approval ask.
 */
ask: AskId, 
/**
 * Its task.
 */
task?: TaskId, 
/**
 * Which attempt, from 1.
 */
attempt: number, } } | { "type": "write_retry_requested", "data": { 
/**
 * The write's approval ask.
 */
ask: AskId, 
/**
 * Its task.
 */
task?: TaskId, 
/**
 * The person who asked.
 */
by: MemberId, } } | { "type": "write_finished", "data": { 
/**
 * The write's approval ask.
 */
ask: AskId, 
/**
 * Its task.
 */
task?: TaskId, 
/**
 * What came of it.
 */
result: WriteResult, } };
