// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Event } from "./Event.ts";

/**
 * `GET /v1/events`: a page of the activity log, oldest first within the page.
 *
 * Page backwards by passing `from_rev` as `before`. Only `at_start` ends paging: with filters, a
 * page may hold fewer than `limit` events (even none) while older matches still exist.
 */
export type EventsPage = { 
/**
 * The events, oldest first.
 */
events: Array<Event>, 
/**
 * Revision of the first returned event; with no events, where the scan stopped (0 at the
 * start of the log).
 */
from_rev: number, 
/**
 * Revision of the last returned event, or 0 when the page is empty.
 */
to_rev: number, 
/**
 * True when no older matching event exists.
 */
at_start: boolean, };
