// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalSystem } from "./ExternalSystem.ts";

/**
 * A link to an item in an external system.
 */
export type ExternalRef = { 
/**
 * The system.
 */
system: ExternalSystem, 
/**
 * The item's key in that system, e.g. `owner/repo#12`, `PROJ-7`, or a milestone name.
 */
key: string, 
/**
 * A link to open it.
 */
url?: string, };
