// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AskId } from "./AskId.ts";
import type { AskKind } from "./AskKind.ts";
import type { BriefTarget } from "./BriefTarget.ts";
import type { Check } from "./Check.ts";
import type { DispatchOutcome } from "./DispatchOutcome.ts";
import type { Health } from "./Health.ts";
import type { MemberId } from "./MemberId.ts";
import type { TaskId } from "./TaskId.ts";
import type { TaskStatus } from "./TaskStatus.ts";
import type { WorkstreamId } from "./WorkstreamId.ts";
import type { WorkstreamStatus } from "./WorkstreamStatus.ts";

/**
 * What a fact says. Repeated facts about the same thing in one block are merged: two moves of
 * one task become one move from the first status to the last.
 */
export type FactKind = { "type": "session_started", 
/**
 * Its title, cleaned.
 */
title?: string, } | { "type": "session_linked", 
/**
 * The workstream.
 */
workstream?: WorkstreamId, 
/**
 * The task.
 */
task?: TaskId, } | { "type": "session_waiting", 
/**
 * The last status line, cleaned.
 */
status_line?: string, } | { "type": "session_ended" } | { "type": "dispatch_started", 
/**
 * The task.
 */
task: TaskId, 
/**
 * The agent.
 */
agent: MemberId, } | { "type": "dispatch_finished", 
/**
 * The task, if the dispatch is known.
 */
task?: TaskId, 
/**
 * How it ended.
 */
outcome: DispatchOutcome, 
/**
 * The agent's closing summary, cleaned.
 */
summary?: string, } | { "type": "task_created", 
/**
 * The task.
 */
task: TaskId, } | { "type": "task_moved", 
/**
 * The task.
 */
task: TaskId, 
/**
 * Status before the first move.
 */
from: TaskStatus, 
/**
 * Status after the last move.
 */
to: TaskStatus, } | { "type": "task_assigned", 
/**
 * The task.
 */
task: TaskId, 
/**
 * The latest assignee.
 */
assignee?: MemberId, } | { "type": "plan_updated", 
/**
 * The task.
 */
task: TaskId, 
/**
 * Subtasks done, in the latest plan.
 */
done: number, 
/**
 * Subtasks in the latest plan.
 */
total: number, } | { "type": "checks", 
/**
 * Which kind.
 */
check: Check, 
/**
 * Runs.
 */
runs: number, 
/**
 * Runs that failed.
 */
failures: number, 
/**
 * Whether the latest run failed.
 */
last_failed: boolean, } | { "type": "job_diverged", 
/**
 * Job ids named by the evidence, cleaned (capped).
 */
jobs: Array<string>, } | { "type": "ask_raised", 
/**
 * The ask.
 */
ask: AskId, 
/**
 * Its kind.
 */
ask_kind: AskKind, 
/**
 * Who must answer.
 */
to: MemberId, 
/**
 * Its title, cleaned.
 */
title: string, } | { "type": "ask_answered", 
/**
 * The ask.
 */
ask: AskId, } | { "type": "commented", 
/**
 * On this task.
 */
task?: TaskId, 
/**
 * Or on this workstream.
 */
workstream?: WorkstreamId, 
/**
 * Members mentioned (capped).
 */
mentions: Array<MemberId>, } | { "type": "decision_recorded", 
/**
 * The decision, cleaned.
 */
text: string, } | { "type": "workstream_created", 
/**
 * The workstream.
 */
workstream: WorkstreamId, } | { "type": "workstream_changed", 
/**
 * The workstream.
 */
workstream: WorkstreamId, 
/**
 * Latest status.
 */
status: WorkstreamStatus, 
/**
 * Latest health.
 */
health: Health, } | { "type": "brief_accepted", 
/**
 * Which brief.
 */
target: BriefTarget, 
/**
 * Whether it was pinned.
 */
pinned: boolean, };
