// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FactKind } from "./FactKind.ts";
import type { MemberId } from "./MemberId.ts";
import type { Receipt } from "./Receipt.ts";

/**
 * A notable fact, with the evidence for it.
 */
export type Fact = { 
/**
 * Who did it: the author of the event (for merged facts, of the first one).
 */
by: MemberId, 
/**
 * When it (first) happened.
 */
at: number, 
/**
 * What happened.
 */
kind: FactKind, 
/**
 * Evidence: always the event, plus any transcript, job or file receipts it carries.
 */
receipts: Array<Receipt>, };
