// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Receipt } from "./Receipt.ts";

/**
 * One file edited in a block.
 */
export type FileTouch = { 
/**
 * Path as the agent reported it, cleaned and capped (the end is kept).
 */
path: string, 
/**
 * Edits to it.
 */
edits: number, 
/**
 * Lines added.
 */
added: number, 
/**
 * Lines removed.
 */
removed: number, 
/**
 * The edit events: the first and the latest.
 */
receipts: Array<Receipt>, };
