// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileKind } from "./FileKind.ts";

/**
 * A directory entry, without following links.
 */
export type FileEntry = { 
/**
 * UTF-8 name.
 */
name: string, 
/**
 * Entry type.
 */
kind: FileKind, 
/**
 * Byte size from metadata.
 */
size: number, 
/**
 * UTC milliseconds, if available.
 */
modified_at: number | null, };
