// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileEncoding } from "./FileEncoding.ts";

/**
 * File bytes and optimistic concurrency revision.
 */
export type FileContent = { 
/**
 * Decoded size.
 */
size: number, 
/**
 * Conservative media type.
 */
media_type: string, 
/**
 * Lowercase SHA-256 of exact bytes.
 */
revision: string, 
/**
 * Content encoding.
 */
encoding: FileEncoding, 
/**
 * Text or base64.
 */
content: string, };
