// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How bytes are carried inside JSON.
 */
export type FileEncoding = "utf8" | "base64";
