// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileEntry } from "./FileEntry.ts";

/**
 * A bounded directory listing.
 */
export type FileList = { 
/**
 * Sorted by UTF-8 bytes.
 */
entries: Array<FileEntry>, 
/**
 * Entries were omitted at the cap.
 */
truncated: boolean, };
