// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Sessions found with one working directory.
 */
export type FolderCount = { 
/**
 * The `cwd`.
 */
path: string, 
/**
 * Sessions found.
 */
count: number, };
