// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Health of an active workstream. It is derived from events, and a person can override it.
 */
export type Health = "on_track" | "at_risk" | "blocked";
