// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Engine } from "./Engine.ts";

/**
 * Sessions found under one account home.
 */
export type HomeCount = { 
/**
 * The CLI.
 */
engine: Engine, 
/**
 * The home folder (`~/.claude`, `~/.codex`, OpenCode's data folder, or one an environment
 * variable names).
 */
home: string, 
/**
 * Sessions found.
 */
count: number, };
