// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Exact text shown before a hook installation.
 */
export type HooksDiffFile = { 
/**
 * Configuration path on the hub's machine.
 */
path: string, 
/**
 * Absent for a new file.
 */
before: string | null, 
/**
 * Proposed replacement, without normalization.
 */
after: string, };
