// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One discovered engine's installer status.
 */
export type HooksEngine = { 
/**
 * CLI name.
 */
engine: string, 
/**
 * Installer status, including conflicting configurations.
 */
status: string, 
/**
 * Explanation, never logged by the route.
 */
detail: string, };
