// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HooksDiffFile } from "./HooksDiffFile.ts";
import type { HooksEngine } from "./HooksEngine.ts";

/**
 * Server-held plan's preview.
 */
export type HooksDiff = { 
/**
 * Opaque revision, bound to the person and machine.
 */
revision: string, 
/**
 * Exact files changed.
 */
files: Array<HooksDiffFile>, 
/**
 * All discovered engines, even when no change is needed.
 */
engines: Array<HooksEngine>, };
