// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Capability } from "./Capability.ts";
import type { HostRole } from "./HostRole.ts";
import type { MachineInfo } from "./MachineInfo.ts";

/**
 * `GET /v1/host/info`: available before authentication, so version skew can be detected early.
 */
export type HostInfo = { 
/**
 * Always `pitcrewd`.
 */
name: string, 
/**
 * Daemon version.
 */
version: string, 
/**
 * Protocol version it speaks.
 */
protocol: number, 
/**
 * Oldest protocol it accepts.
 */
protocol_min: number, 
/**
 * Roles.
 */
roles: Array<HostRole>, 
/**
 * Machine facts.
 */
machine: MachineInfo, 
/**
 * Runner capabilities.
 */
capabilities: Array<Capability>, };
