// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The roles a daemon plays (ADR-0009). A solo workspace runs both in one process.
 */
export type HostRole = "hub" | "runner";
