// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommandId } from "./CommandId.ts";
import type { RunnerCommand } from "./RunnerCommand.ts";

/**
 * Messages from a hub to a runner.
 */
export type HubToRunner = { "type": "welcome", 
/**
 * The hub's version.
 */
hub_version: string, 
/**
 * The protocol version both will use.
 */
protocol: number, 
/**
 * Resend events after this cursor.
 */
resume_after_cursor: number, } | { "type": "command", 
/**
 * Id and idempotency key.
 */
id: CommandId, 
/**
 * What to do.
 */
command: RunnerCommand, } | { "type": "ack_events", 
/**
 * Stored up to here.
 */
cursor: number, };
