// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How existing and future sessions are included.
 */
export type ImportMode = "all" | "filtered" | "none";
