// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Committed count.
 */
export type ImportResult = { 
/**
 * Included indexed sessions, sub-agents left out: they come with their parents.
 */
imported: number, 
/**
 * Included sub-agent sessions, nested under the sessions counted in `imported`.
 */
subagents: number, };
