// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Dry run count.
 */
export type ImportDryRun = { 
/**
 * Included indexed sessions.
 */
count: number, };
