// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Committed count.
 */
export type ImportResult = { 
/**
 * Included indexed sessions.
 */
imported: number, };
