// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportFilter } from "./ImportFilter.ts";

/**
 * The durable choice and its fresh-start boundary.
 */
export type ImportChoice = { 
/**
 * Inclusion rules.
 */
filter: ImportFilter, 
/**
 * Commit time, absent before the first choice.
 */
committed_at: number | null, };
