// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Dry run count.
 */
export type ImportDryRun = { 
/**
 * Included indexed sessions, sub-agents left out: they come with their parents.
 */
count: number, 
/**
 * Included sub-agent sessions (those with a `parent`), nested under the sessions counted in
 * `count`.
 */
subagents: number, };
