// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Engine } from "./Engine.ts";
import type { ImportMode } from "./ImportMode.ts";

/**
 * Inclusion rules; empty arrays mean no restriction.
 */
export type ImportFilter = { 
/**
 * The choice.
 */
mode: ImportMode, 
/**
 * Inclusive UTC calendar date.
 */
since?: string, 
/**
 * Allowed engines.
 */
engines?: Array<Engine>, 
/**
 * Working directories and their descendants.
 */
folders?: Array<string>, };
