// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Confirmation of a previously displayed plan.
 */
export type InstallHooks = { 
/**
 * Revision from the preview.
 */
revision: string, };
