// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A connection to GitHub or Jira (api-v1.md, "Integrations").
 */
export type IntegrationId = string;
