// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JiraDeployment } from "./JiraDeployment.ts";

/**
 * What an integration syncs. On the wire, tagged by `kind`.
 */
export type IntegrationSettings = { "kind": "github", 
/**
 * `owner/repo`, distinct.
 */
repos: Array<string>, 
/**
 * A GitHub Enterprise Server API root; absent means `https://api.github.com`.
 */
api_base?: string, } | { "kind": "jira", 
/**
 * Cloud or Data Center.
 */
deployment: JiraDeployment, 
/**
 * The site's root, e.g. `https://jira.example.com`.
 */
site: string, 
/**
 * Project keys, distinct.
 */
projects: Array<string>, 
/**
 * The account e-mail (Cloud only).
 */
email?: string, 
/**
 * Data Center's epic link field, e.g. `customfield_10008`.
 */
epic_link_field?: string, };
