// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CredentialInfo } from "./CredentialInfo.ts";
import type { IntegrationId } from "./IntegrationId.ts";
import type { IntegrationLink } from "./IntegrationLink.ts";
import type { IntegrationSettings } from "./IntegrationSettings.ts";
import type { MemberId } from "./MemberId.ts";
import type { SyncStatus } from "./SyncStatus.ts";

/**
 * A connection to GitHub or Jira, as the routes return it.
 */
export type Integration = { 
/**
 * Id.
 */
id: IntegrationId, 
/**
 * Name.
 */
name: string, 
/**
 * What it syncs.
 */
settings: IntegrationSettings, 
/**
 * Where its credential comes from.
 */
credential: CredentialInfo, 
/**
 * Minutes between syncs.
 */
interval_minutes: number, 
/**
 * The person who added it; conflicts are asked of them.
 */
added_by: MemberId, 
/**
 * When.
 */
added_at: number, 
/**
 * Its sync.
 */
status: SyncStatus, 
/**
 * The workstream links it syncs.
 */
links: Array<IntegrationLink>, };
