// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalRef } from "./ExternalRef.ts";
import type { WorkstreamId } from "./WorkstreamId.ts";

/**
 * A workstream link an integration syncs.
 */
export type IntegrationLink = { 
/**
 * The workstream.
 */
workstream: WorkstreamId, 
/**
 * The upstream scope it links: a repository, a milestone, a Jira project or an epic.
 */
scope: ExternalRef, 
/**
 * The upstream title, once a sync has seen it.
 */
title?: string, };
