// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScopeCheck } from "./ScopeCheck.ts";

/**
 * `POST /v1/integrations/{id}/test`: one read of upstream with the credential.
 */
export type IntegrationCheck = { 
/**
 * Every check passed.
 */
ok: boolean, 
/**
 * When.
 */
at: number, 
/**
 * The checks.
 */
checks: Array<ScopeCheck>, 
/**
 * The credential can do more than read.
 */
warnings: Array<string>, };
