// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An issue's state, as a write sets it.
 */
export type IssueState = "open" | "closed";
