// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which Jira a connection talks to.
 */
export type JiraDeployment = "cloud" | "data_center";
