// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A key to send to a terminal.
 */
export type Key = "enter" | "escape" | "tab" | "up" | "down" | "left" | "right" | "backspace" | "ctrl_c";
