// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a session is linked to a workstream or task. Links made by a person or a dispatch are never
 * overridden by inference.
 */
export type LinkBasis = "dispatch" | "claimed" | "manual" | "folder" | "branch" | "imported";
