// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a machine can be reached. **Loss of contact is not death:** an unreachable machine is
 * `Unverifiable`, and its last known state is still shown.
 */
export type Liveness = "live" | "unverifiable" | "stopped";
