// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MachineId } from "./MachineId.ts";

/**
 * A folder (and optionally a git branch) on a machine. This is how sessions are linked to
 * projects and workstreams.
 */
export type Location = { 
/**
 * The machine.
 */
machine: MachineId, 
/**
 * Absolute path on that machine.
 */
path: string, 
/**
 * The git branch, when the location is branch-specific.
 */
branch?: string, };
