// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Liveness } from "./Liveness.ts";
import type { MachineId } from "./MachineId.ts";
import type { MachineInfo } from "./MachineInfo.ts";
import type { MachineKind } from "./MachineKind.ts";

/**
 * A machine known to a workspace.
 */
export type Machine = { 
/**
 * Id.
 */
id: MachineId, 
/**
 * Display name, e.g. "This PC" or "cluster".
 */
name: string, 
/**
 * How it is reached.
 */
kind: MachineKind, 
/**
 * Last reported facts.
 */
info?: MachineInfo, 
/**
 * Whether it can be reached now.
 */
liveness: Liveness, };
