// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a check row is about.
 */
export type MachineCheckItem = "cli_claude" | "cli_codex" | "cli_opencode" | "tmux" | "git" | "gh" | "disk" | "slurm" | "helper";
