// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Scheduler } from "./Scheduler.ts";

/**
 * Facts a runner reports about its machine.
 */
export type MachineInfo = { 
/**
 * Host name as the machine reports it.
 */
hostname: string, 
/**
 * Operating system, e.g. `linux`, `macos`, `windows`.
 */
os: string, 
/**
 * CPU architecture, e.g. `x86_64`, `aarch64`.
 */
arch: string, 
/**
 * Whether `tmux` is available.
 */
has_tmux: boolean, 
/**
 * The batch scheduler, if any.
 */
scheduler?: Scheduler, 
/**
 * Whether the home directory is on a network filesystem (e.g. NFS). This changes storage
 * rules; see ADR-0004.
 */
home_on_network_fs: boolean, };
