// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MachineCheckFix } from "./MachineCheckFix.ts";
import type { MachineCheckItem } from "./MachineCheckItem.ts";
import type { MachineCheckStatus } from "./MachineCheckStatus.ts";

/**
 * One thing the check looked at.
 */
export type MachineCheckRow = { 
/**
 * What the row is about.
 */
id: MachineCheckItem, 
/**
 * How it stands.
 */
status: MachineCheckStatus, 
/**
 * A short reason for people: the version found, the free space, or what is wrong. Plain
 * text, at most a line.
 */
detail: string, 
/**
 * The tool's version as it printed it (its first line, cleaned), when it ran.
 */
version?: string, 
/**
 * What PitCrew can do about it, when anything. Absent on an `ok` row.
 */
fix?: MachineCheckFix, };
