// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MachineCheckRow } from "./MachineCheckRow.ts";

/**
 * `GET /v1/machines/{id}/check`'s answer.
 */
export type MachineCheck = { 
/**
 * The rows, in a fixed order: the agent CLIs, tmux, git, gh, disk, then SLURM where the
 * machine has it (and PitCrew's helper, in a check made before it is installed).
 */
rows: Array<MachineCheckRow>, };
