// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What PitCrew can do about a row. Never installing a system package: the person does that.
 */
export type MachineCheckFix = "install_page" | "install_helper";
