// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A machine with a runner: this PC, a WSL distro, a server, an HPC login node.
 */
export type MachineId = string;
