// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a member is a person or an agent.
 */
export type MemberKind = "human" | "agent";
