// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Avatar } from "./Avatar.ts";
import type { MemberId } from "./MemberId.ts";
import type { MemberKind } from "./MemberKind.ts";
import type { PersonaId } from "./PersonaId.ts";

/**
 * A member of a workspace. People and agents share this shape.
 */
export type Member = { 
/**
 * Id.
 */
id: MemberId, 
/**
 * Person or agent.
 */
kind: MemberKind, 
/**
 * Unique handle within the workspace, e.g. `@writer`.
 */
handle: string, 
/**
 * Display name.
 */
name: string, 
/**
 * The owning person. Required for agents; absent for people.
 */
owner?: MemberId, 
/**
 * The persona an agent was created from.
 */
persona?: PersonaId, 
/**
 * Optional initials and colour chosen in Profile settings.
 */
avatar?: Avatar, };
