// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Sessions started in one calendar month, UTC.
 */
export type MonthCount = { 
/**
 * `YYYY-MM`.
 */
month: string, 
/**
 * Sessions found.
 */
count: number, };
