// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to advance a person's cursor.
 */
export type MoveCursor = { 
/**
 * Last seen log revision.
 */
rev: number, };
