// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who is asking to move a task. The hub checks every move with [`TaskStatus::can_move`].
 */
export type Mover = { "kind": "person" } | { "kind": "agent", 
/**
 * Whether the task is the agent's own.
 */
on_own_task: boolean, } | { "kind": "back_office", 
/**
 * Whether the task may be accepted without a person.
 */
accept_auto: boolean, } | { "kind": "sync" };
