// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `PUT /v1/integrations/{id}/credential`. Its `Debug` never shows the secret.
 */
export type NewCredential = { 
/**
 * The secret: a token, an API token or a personal access token.
 */
secret: string, };
