// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CredentialSource } from "./CredentialSource.ts";
import type { IntegrationSettings } from "./IntegrationSettings.ts";

/**
 * `POST /v1/integrations`.
 */
export type NewIntegration = { 
/**
 * A name for people, 1–80 characters.
 */
name: string, 
/**
 * What to sync.
 */
settings: IntegrationSettings, 
/**
 * Where the credential comes from.
 */
credential: CredentialSource, 
/**
 * Minutes between syncs, 5–1440; 15 when absent.
 */
interval_minutes?: number, };
