// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Date } from "./Date.ts";
import type { Location } from "./Location.ts";
import type { MemberId } from "./MemberId.ts";
import type { ProjectKey } from "./ProjectKey.ts";
import type { ProjectStatus } from "./ProjectStatus.ts";

/**
 * `POST /v1/projects`: a new project. The hub assigns the id.
 */
export type NewProject = { 
/**
 * Key used in task keys; unique in the workspace.
 */
key: ProjectKey, 
/**
 * Name.
 */
name: string, 
/**
 * The lead; the caller if absent.
 */
lead?: MemberId, 
/**
 * Members; the lead alone if absent. The lead is always a member.
 */
members?: Array<MemberId>, 
/**
 * Status; `in_progress` if absent.
 */
status?: ProjectStatus, 
/**
 * Start date.
 */
start?: Date, 
/**
 * Due date.
 */
due?: Date, 
/**
 * The root folder.
 */
root?: Location, 
/**
 * Optional first workstream, committed atomically with the project.
 */
first_workstream?: string, };
