// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Date } from "./Date.ts";
import type { MemberId } from "./MemberId.ts";
import type { Priority } from "./Priority.ts";
import type { ProjectId } from "./ProjectId.ts";
import type { TaskStatus } from "./TaskStatus.ts";
import type { WorkstreamId } from "./WorkstreamId.ts";

/**
 * `POST /v1/tasks`: a new task. The hub assigns the id and the next key in the project.
 */
export type NewTask = { 
/**
 * The project.
 */
project: ProjectId, 
/**
 * The workstream; it must belong to the project.
 */
workstream?: WorkstreamId, 
/**
 * Title.
 */
title: string, 
/**
 * Description; empty if absent.
 */
description?: string, 
/**
 * Status; `todo` if absent.
 */
status?: TaskStatus, 
/**
 * Priority; `none` if absent.
 */
priority?: Priority, 
/**
 * Assignee.
 */
assignee?: MemberId, 
/**
 * Labels; none if absent.
 */
labels?: Array<string>, 
/**
 * Due date.
 */
due?: Date, };
