// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskId } from "./TaskId.ts";
import type { WriteOperation } from "./WriteOperation.ts";

/**
 * `POST /v1/writes`: a person asks for a write.
 */
export type NewWrite = { 
/**
 * The task.
 */
task: TaskId, 
/**
 * `create_issue` or `comment`.
 */
operation: WriteOperation, 
/**
 * A comment's text.
 */
text?: string, };
