// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Location } from "./Location.ts";
import type { ProjectId } from "./ProjectId.ts";
import type { WorkstreamStatus } from "./WorkstreamStatus.ts";

/**
 * `POST /v1/workstreams`: a new workstream in a project. The hub assigns the id; its health
 * starts `on_track`.
 */
export type NewWorkstream = { 
/**
 * The project.
 */
project: ProjectId, 
/**
 * Name.
 */
name: string, 
/**
 * Status; `active` if absent.
 */
status?: WorkstreamStatus, 
/**
 * Folders or branches whose sessions belong to it; none if absent.
 */
locations?: Array<Location>, };
