// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnswerReference } from "./AnswerReference.ts";
import type { AnswerSuggestion } from "./AnswerSuggestion.ts";
import type { AnswerUsage } from "./AnswerUsage.ts";
import type { SessionId } from "./SessionId.ts";
import type { TurnState } from "./TurnState.ts";

/**
 * One question and its answer.
 */
export type OrchestratorTurn = { 
/**
 * The question, as sent to the CLI.
 */
question: string, 
/**
 * When it was asked.
 */
asked: number, 
/**
 * The session that answers it.
 */
session: SessionId, 
/**
 * Where it stands.
 */
state: TurnState, 
/**
 * The answer so far, from the session's transcript; untrusted text, shown as text.
 */
answer: string, 
/**
 * What the answer cites that the hub knows.
 */
references: Array<AnswerReference>, 
/**
 * Actions the answer suggests: they do nothing unless the person clicks one.
 */
suggestions: Array<AnswerSuggestion>, 
/**
 * What it took, once it has ended.
 */
usage?: AnswerUsage, 
/**
 * When it ended.
 */
ended?: number, 
/**
 * Why it ended, when it did not end with an answer.
 */
note?: string, };
