// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The Orchestrator's bounds.
 */
export type OrchestratorLimits = { 
/**
 * [`MAX_QUESTION_CHARS`].
 */
question_chars: number, 
/**
 * [`MAX_ANSWER_BYTES`].
 */
answer_bytes: number, 
/**
 * [`MAX_ANSWER_SECONDS`].
 */
answer_seconds: number, 
/**
 * [`MAX_TURNS`].
 */
turns: number, 
/**
 * [`MAX_CONVERSATIONS`].
 */
conversations: number, };
