// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Conversation } from "./Conversation.ts";
import type { Engine } from "./Engine.ts";
import type { EngineStatus } from "./EngineStatus.ts";
import type { OrchestratorLimits } from "./OrchestratorLimits.ts";

/**
 * `GET /v1/orchestrator`: the caller's own.
 */
export type Orchestrator = { 
/**
 * Each agent CLI, and whether it is installed where questions run.
 */
engines: Array<EngineStatus>, 
/**
 * The engine the caller chose last for a new conversation: the next one's default.
 */
engine?: Engine, 
/**
 * The bounds.
 */
limits: OrchestratorLimits, 
/**
 * The caller's conversations, newest first.
 */
conversations: Array<Conversation>, };
