// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How an agent CLI handles permission prompts. The default is the CLI's own behaviour, which
 * asks. Bypassing is an explicit per-workspace opt-in.
 */
export type PermissionMode = "default" | "accept_edits" | "plan" | "bypass_permissions";
