// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Engine } from "./Engine.ts";
import type { PermissionMode } from "./PermissionMode.ts";
import type { PersonaId } from "./PersonaId.ts";

/**
 * A reusable recipe for new agents.
 */
export type Persona = { 
/**
 * Id.
 */
id: PersonaId, 
/**
 * Name, e.g. "Writer".
 */
name: string, 
/**
 * The CLI to run.
 */
engine: Engine, 
/**
 * Model identifier passed to the CLI, if not its default.
 */
model?: string, 
/**
 * Standing instructions given to every agent made from this persona.
 */
instructions?: string, 
/**
 * Permission mode.
 */
permission_mode: PermissionMode, };
