// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Engine } from "./Engine.ts";
import type { PermissionMode } from "./PermissionMode.ts";

/**
 * Editable fields of an agent recipe; the hub assigns the id.
 */
export type PersonaEdit = { 
/**
 * Display name.
 */
name: string, 
/**
 * CLI engine.
 */
engine: Engine, 
/**
 * Optional model identifier.
 */
model?: string, 
/**
 * Optional standing instructions.
 */
instructions?: string, 
/**
 * CLI permission policy, explicitly selected by the person.
 */
permission_mode: PermissionMode, };
