// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlanStatus } from "./PlanStatus.ts";

/**
 * One line of an agent's plan.
 */
export type PlanItem = { 
/**
 * Text.
 */
text: string, 
/**
 * Status.
 */
status: PlanStatus, };
