// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Priority of a task.
 */
export type Priority = "urgent" | "high" | "medium" | "low" | "none";
