// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A project: a deliverable, such as a paper, a thesis part or a product.
 */
export type ProjectId = string;
