// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Status of a project.
 */
export type ProjectStatus = "planning" | "in_progress" | "on_hold" | "completed";
