// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Date } from "./Date.ts";
import type { ExternalRef } from "./ExternalRef.ts";
import type { Location } from "./Location.ts";
import type { MemberId } from "./MemberId.ts";
import type { ProjectId } from "./ProjectId.ts";
import type { ProjectKey } from "./ProjectKey.ts";
import type { ProjectStatus } from "./ProjectStatus.ts";

/**
 * A project: a deliverable such as a paper, a thesis part or a product.
 */
export type Project = { 
/**
 * Id.
 */
id: ProjectId, 
/**
 * Key used in task keys.
 */
key: ProjectKey, 
/**
 * Name.
 */
name: string, 
/**
 * Status.
 */
status: ProjectStatus, 
/**
 * The lead member.
 */
lead: MemberId, 
/**
 * Members working on it.
 */
members: Array<MemberId>, 
/**
 * Start date.
 */
start?: Date, 
/**
 * Due date.
 */
due?: Date, 
/**
 * The root folder.
 */
root?: Location, 
/**
 * Linked external items, such as a repository or a Jira project.
 */
external: Array<ExternalRef>, };
