// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A short project key used in task keys, such as `CMP` in `CMP-104`.
 *
 * Rules: 2–10 characters, the first an uppercase ASCII letter, the rest uppercase letters or
 * digits.
 */
export type ProjectKey = string;
