// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionId } from "./SessionId.ts";
import type { TaskStatus } from "./TaskStatus.ts";

/**
 * One task a draft proposes.
 */
export type ProposedTask = { 
/**
 * Its title.
 */
title: string, 
/**
 * Where it stands: `backlog`, `todo`, `in_progress`, `review` or `done` (never `canceled`).
 */
status: TaskStatus, 
/**
 * What it is about, if the agent says.
 */
description?: string, 
/**
 * The workstream's sessions it is drawn from.
 */
evidence: Array<SessionId>, };
