// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConversationId } from "./ConversationId.ts";
import type { Engine } from "./Engine.ts";
import type { MemberId } from "./MemberId.ts";

/**
 * `POST /v1/orchestrator/questions`.
 */
export type Question = { 
/**
 * The question.
 */
text: string, 
/**
 * The CLI for a new conversation; the remembered one, else `claude`, when absent. A
 * follow-up keeps its conversation's.
 */
engine?: Engine, 
/**
 * The conversation to follow up in; a new conversation when absent.
 */
conversation?: ConversationId, 
/**
 * The agent the session runs as: one of the caller's own. The caller's back office when
 * absent.
 */
agent?: MemberId, };
