// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The revision a person has read in a workspace, project or workstream.
 */
export type ReadCursor = { 
/**
 * `workspace`, `project:<id>` or `workstream:<id>`.
 */
scope: string, 
/**
 * Last seen log revision; only moves forward.
 */
rev: number, };
