// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Block } from "./Block.ts";
import type { Summary } from "./Summary.ts";

/**
 * A block with its one-line summary.
 */
export type RecapBlock = { 
/**
 * The block.
 */
block: Block, 
/**
 * Its line, e.g. "@writer edited method.tex (+84 −12)".
 */
line: Summary, };
