// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventId } from "./EventId.ts";
import type { Location } from "./Location.ts";
import type { Scheduler } from "./Scheduler.ts";
import type { SessionId } from "./SessionId.ts";

/**
 * Evidence behind a claim. Every recap line and every "Where it stands" links to receipts.
 */
export type Receipt = { "kind": "transcript", 
/**
 * The session.
 */
session: SessionId, 
/**
 * Byte offset of the record.
 */
offset: number, } | { "kind": "commit", 
/**
 * Repository, as a path or URL.
 */
repo: string, 
/**
 * Commit hash.
 */
sha: string, } | { "kind": "pull_request", 
/**
 * Link.
 */
url: string, } | { "kind": "job", 
/**
 * The scheduler.
 */
scheduler: Scheduler, 
/**
 * The job id.
 */
id: string, } | { "kind": "file", 
/**
 * Where it is.
 */
location: Location, } | { "kind": "event", 
/**
 * The event id.
 */
id: EventId, };
