// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a session's transcript records about it ([`Session::recorded`]).
 */
export type Recorded = { 
/**
 * The model, as the transcript last recorded it (e.g. `claude-sonnet-4-5`); it changes with
 * `session_updated`.
 */
model?: string, 
/**
 * The CLI account home its transcript is in (`~/.claude`, or a `CLAUDE_CONFIG_DIR`,
 * `CODEX_HOME` or OpenCode data folder): which account ran it, where a machine has several.
 * `~` stands for the machine user's home.
 */
account?: string, };
