// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Date } from "./Date.ts";
import type { ProjectId } from "./ProjectId.ts";
import type { SessionId } from "./SessionId.ts";
import type { TaskId } from "./TaskId.ts";
import type { TaskKey } from "./TaskKey.ts";
import type { WorkstreamId } from "./WorkstreamId.ts";

/**
 * What a reference points to. Each is an app route: the console's session, a task, a
 * workstream, a project, or a workstream's or project's recap.
 */
export type ReferenceTarget = { "kind": "session", 
/**
 * Its id.
 */
id: SessionId, } | { "kind": "task", 
/**
 * Its id.
 */
id: TaskId, 
/**
 * Its key.
 */
key: TaskKey, } | { "kind": "workstream", 
/**
 * Its id.
 */
id: WorkstreamId, 
/**
 * Its project.
 */
project: ProjectId, } | { "kind": "project", 
/**
 * Its id.
 */
id: ProjectId, } | { "kind": "recap", 
/**
 * The project.
 */
project: ProjectId, 
/**
 * The workstream, for a workstream's recap.
 */
workstream?: WorkstreamId, 
/**
 * The day.
 */
date?: Date, };
