// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EndMode } from "./EndMode.ts";
import type { Engine } from "./Engine.ts";
import type { Key } from "./Key.ts";
import type { PermissionMode } from "./PermissionMode.ts";
import type { PersonaId } from "./PersonaId.ts";
import type { SessionId } from "./SessionId.ts";
import type { TerminalId } from "./TerminalId.ts";

/**
 * Commands a hub sends to a runner.
 */
export type RunnerCommand = { "type": "start_session", 
/**
 * The CLI.
 */
engine: Engine, 
/**
 * Working directory.
 */
cwd: string, 
/**
 * Session name, which the CLI also sees where supported.
 */
name: string, 
/**
 * First prompt.
 */
brief?: string, 
/**
 * Persona it is made from.
 */
persona?: PersonaId, 
/**
 * Model override.
 */
model?: string, 
/**
 * Which CLI account home to use (e.g. a `CLAUDE_CONFIG_DIR`). The runner resolves it;
 * secrets never travel in commands.
 */
account?: string, 
/**
 * Permission mode.
 */
permission_mode: PermissionMode, 
/**
 * The id the new session must be reported under: one the hub has already stored (a
 * dispatch's, or a start for an agent or a task), in state `starting`. The runner adopts
 * it for the CLI's transcript instead of minting one, so the session is never discovered
 * a second time under another id. Without it, the runner mints the id when the
 * transcript appears.
 */
session?: SessionId, } | { "type": "resume_session", 
/**
 * The CLI.
 */
engine: Engine, 
/**
 * The CLI's session id.
 */
native_id: string, 
/**
 * Working directory.
 */
cwd: string, 
/**
 * Session name.
 */
name: string, } | { "type": "send_text", 
/**
 * The session.
 */
session: SessionId, 
/**
 * Text.
 */
text: string, } | { "type": "send_keys", 
/**
 * The session.
 */
session: SessionId, 
/**
 * Keys, in order.
 */
keys: Array<Key>, } | { "type": "interrupt", 
/**
 * The session.
 */
session: SessionId, } | { "type": "end_session", 
/**
 * The session.
 */
session: SessionId, 
/**
 * How.
 */
mode: EndMode, } | { "type": "resize_terminal", 
/**
 * The terminal.
 */
terminal: TerminalId, 
/**
 * Columns.
 */
cols: number, 
/**
 * Rows.
 */
rows: number, } | { "type": "read_terminal", 
/**
 * The terminal.
 */
terminal: TerminalId, 
/**
 * Start offset.
 */
from_offset: number, 
/**
 * Maximum bytes to return.
 */
max_bytes: number, } | { "type": "scan", 
/**
 * Roots.
 */
roots: Array<string>, };
