// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Capability } from "./Capability.ts";
import type { CommandId } from "./CommandId.ts";
import type { CommandOutcome } from "./CommandOutcome.ts";
import type { Event } from "./Event.ts";
import type { MachineInfo } from "./MachineInfo.ts";
import type { TerminalId } from "./TerminalId.ts";

/**
 * Messages from a runner to its hub.
 */
export type RunnerToHub = { "type": "hello", 
/**
 * The runner's version.
 */
runner_version: string, 
/**
 * Protocol version it speaks.
 */
protocol: number, 
/**
 * Facts about the machine.
 */
machine: MachineInfo, 
/**
 * What it can do.
 */
capabilities: Array<Capability>, } | { "type": "events", 
/**
 * The events, in order.
 */
events: Array<Event>, 
/**
 * Position after this batch.
 */
cursor: number, } | { "type": "command_result", 
/**
 * The command.
 */
command: CommandId, 
/**
 * Outcome.
 */
outcome: CommandOutcome, } | { "type": "terminal_output", 
/**
 * The terminal.
 */
terminal: TerminalId, 
/**
 * Offset of the first byte.
 */
offset: number, 
/**
 * The bytes, base64-encoded.
 */
data_b64: string, } | { "type": "heartbeat", 
/**
 * Runner time.
 */
at: number, };
