// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackOfficeCaps } from "./BackOfficeCaps.ts";
import type { WorkspacePermissionMode } from "./WorkspacePermissionMode.ts";

/**
 * Durable workspace safety settings.
 */
export type SafetySettings = { 
/**
 * Default for a new session without an override.
 */
permissionMode: WorkspacePermissionMode, 
/**
 * Allow low-risk automatic acceptance.
 */
backOfficeEnabled: boolean, 
/**
 * Acceptance budget.
 */
backOfficeCaps: BackOfficeCaps, };
