// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackOfficeCaps } from "./BackOfficeCaps.ts";
import type { PermissionMode } from "./PermissionMode.ts";

/**
 * Durable workspace safety settings.
 */
export type SafetySettings = { 
/**
 * Default for a new session without an override.
 */
permission_mode: PermissionMode, 
/**
 * Allow low-risk automatic acceptance.
 */
back_office_enabled: boolean, 
/**
 * Acceptance budget.
 */
back_office_caps: BackOfficeCaps, };
