// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorCode } from "./ErrorCode.ts";
import type { ScanProgress } from "./ScanProgress.ts";
import type { ScanReport } from "./ScanReport.ts";

/**
 * One frame of a scan's answer: a line of JSON, tagged by `type`.
 */
export type ScanFrame = { "type": "progress" } & ScanProgress | { "type": "done", 
/**
 * Counts and suggestions.
 */
report: ScanReport, } | { "type": "error", 
/**
 * What kind of failure, as in an `ApiError`.
 */
code: ErrorCode, 
/**
 * A sentence for people.
 */
message: string, };
