// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EngineCount } from "./EngineCount.ts";
import type { FolderCount } from "./FolderCount.ts";
import type { HomeCount } from "./HomeCount.ts";
import type { MonthCount } from "./MonthCount.ts";

/**
 * Counts from a scan. `by_engine`, `by_home`, `by_folder` and `by_month` cover ordinary sessions
 * only: a sub-agent session shares its parent's folder and month, so folding it in would double
 * those buckets without adding information. Sub-agent sessions are counted once, separately, in
 * `subagent_sessions`.
 *
 * A sub-agent counts as one only when its parent session was found too (in the same home), since
 * it is shown nested under its parent: one whose transcript names no parent, or a parent the scan
 * did not find, is shown as a session of its own, and counted as one. So these counts are what an
 * import shows.
 */
export type ScanCounts = { 
/**
 * Ordinary sessions found: sessions, and sub-agents whose parent was not found.
 */
sessions: number, 
/**
 * Sub-agent sessions found with their parent, counted separately.
 */
subagent_sessions: number, 
/**
 * Per engine.
 */
by_engine: Array<EngineCount>, 
/**
 * Per account home.
 */
by_home: Array<HomeCount>, 
/**
 * Per folder, busiest first. Folders that are the same real place but spelled differently
 * (a case-insensitive filesystem) are counted together, under one of their spellings.
 */
by_folder: Array<FolderCount>, 
/**
 * Per month, most recent first.
 */
by_month: Array<MonthCount>, 
/**
 * The earliest session start found.
 */
first_activity?: number, 
/**
 * The most recent activity found (a transcript's modification time).
 */
last_activity?: number, };
