// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScanCounts } from "./ScanCounts.ts";
import type { Suggestion } from "./Suggestion.ts";

/**
 * The result of a scan.
 */
export type ScanReport = { 
/**
 * Counts.
 */
counts: ScanCounts, 
/**
 * Suggested projects, most recently active first.
 */
suggestions: Array<Suggestion>, 
/**
 * Folders or transcripts skipped because they could not be read (permission denied, a
 * vanished file, a locked store). Not fatal: the rest of the scan still ran.
 */
unreadable: number, };
