// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One progress tick.
 */
export type ScanProgress = { 
/**
 * Transcripts looked at so far.
 */
scanned: number, 
/**
 * Total transcripts discovered, once discovery (a directory walk) has finished.
 */
total?: number, 
/**
 * A path recently finished, for a "scanning …" line. Best-effort: a tick can land between
 * transcripts and carry nothing.
 */
path?: string, };
