// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One check of `POST /v1/integrations/{id}/test`.
 */
export type ScopeCheck = { 
/**
 * A repository, a Jira project, or `""` for the credential.
 */
scope: string, 
/**
 * It passed.
 */
ok: boolean, 
/**
 * For people to read.
 */
message: string, };
