// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionEngine } from "./SessionEngine.ts";

/**
 * Launch choices advertised by a reachable machine's runner.
 */
export type SessionOptions = { 
/**
 * Absolute path syntax: `windows` or `unix`.
 */
platform: string, 
/**
 * Executable agent CLIs, with their supported permission modes.
 */
engines: Array<SessionEngine>, };
