// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A session: one CLI conversation (Claude Code, Codex, OpenCode) on one machine.
 */
export type SessionId = string;
