// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Engine } from "./Engine.ts";
import type { LinkBasis } from "./LinkBasis.ts";
import type { MachineId } from "./MachineId.ts";
import type { MemberId } from "./MemberId.ts";
import type { SessionId } from "./SessionId.ts";
import type { SessionState } from "./SessionState.ts";
import type { TaskId } from "./TaskId.ts";
import type { TerminalId } from "./TerminalId.ts";
import type { WorkstreamId } from "./WorkstreamId.ts";

/**
 * One CLI conversation on one machine.
 */
export type Session = { 
/**
 * Id.
 */
id: SessionId, 
/**
 * The CLI.
 */
engine: Engine, 
/**
 * The CLI's own session id, used to resume it.
 */
native_id: string, 
/**
 * The machine it runs on.
 */
machine: MachineId, 
/**
 * Working directory.
 */
cwd: string, 
/**
 * Git branch at the start of the session, if any.
 */
branch?: string, 
/**
 * Title, from the CLI or a person.
 */
title?: string, 
/**
 * The agent member running it. Absent for unnamed runs.
 */
agent?: MemberId, 
/**
 * Linked workstream.
 */
workstream?: WorkstreamId, 
/**
 * Linked task.
 */
task?: TaskId, 
/**
 * Why it is linked.
 */
link_basis?: LinkBasis, 
/**
 * Current state.
 */
state: SessionState, 
/**
 * A one-line status, e.g. "Running tests → 212 of 240".
 */
status_line?: string, 
/**
 * When it started.
 */
started: number, 
/**
 * Last observed activity.
 */
last_activity: number, 
/**
 * The terminal it runs in, if the runner owns one.
 */
terminal?: TerminalId, 
/**
 * For a sub-agent's session, the session that started it. A sub-agent is shown nested under
 * its parent, never as an agent of its own; one whose parent could not be found has none,
 * and is shown as a session of its own.
 */
parent?: SessionId, 
/**
 * The model, as the transcript last recorded it (e.g. `claude-sonnet-4-5`). Absent until the
 * transcript records one.
 */
model?: string, 
/**
 * The CLI account home its transcript is in (`~/.claude`, or a `CLAUDE_CONFIG_DIR`,
 * `CODEX_HOME` or OpenCode data folder): which account ran it, where a machine has several.
 * `~` stands for the machine user's home. Absent for a session the runner has not read.
 */
account?: string, };
