// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * State of a session, derived from hooks, transcripts and the terminal.
 */
export type SessionState = "starting" | "working" | "waiting" | "idle" | "ended" | "unreachable";
