// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Engine } from "./Engine.ts";
import type { PermissionMode } from "./PermissionMode.ts";

/**
 * One installed CLI's launch options.
 */
export type SessionEngine = { 
/**
 * CLI engine.
 */
engine: Engine, 
/**
 * Modes supported by this engine and allowed by this runner.
 */
permission_modes: Array<PermissionMode>, };
