// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Machine } from "./Machine.ts";
import type { Member } from "./Member.ts";
import type { Workspace } from "./Workspace.ts";

/**
 * The answer to `POST /v1/setup`.
 */
export type SetupDone = { 
/**
 * The workspace, with its new name.
 */
workspace: Workspace, 
/**
 * The person, as `GET /v1/me` answers from now on.
 */
me: Member, 
/**
 * The hub's own machine.
 */
machine: Machine, };
