// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The person in a [`Setup`].
 */
export type SetupPerson = { 
/**
 * Display name, 1–80 characters.
 */
name: string, 
/**
 * `@` followed by 1–32 of `a-z 0-9 _ -`.
 */
handle: string, };
