// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SetupPerson } from "./SetupPerson.ts";

/**
 * `POST /v1/setup`: the first run of a fresh hub (api-v1.md, "The first run"). The person is the
 * device token's own member; the machine is the hub's own, local one.
 */
export type Setup = { 
/**
 * The workspace's name, 1–80 characters.
 */
workspace_name: string, 
/**
 * The person setting the workspace up.
 */
person: SetupPerson, 
/**
 * This machine's display name, 1–60 characters.
 */
machine_name: string, };
