// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Engine } from "./Engine.ts";
import type { SessionId } from "./SessionId.ts";

/**
 * A sign-in terminal: the CLI's own login, running on the machine.
 */
export type SignIn = { 
/**
 * The CLI.
 */
engine: Engine, 
/**
 * The terminal's id. Its WebSocket is the terminals route,
 * `GET /v1/sessions/{terminal}/terminal`; it is not a session, and no other session route
 * knows it.
 */
terminal: SessionId, 
/**
 * The command it runs, word by word (`["claude", "auth", "login"]`), for people.
 */
command: Array<string>, 
/**
 * Whether the login still runs. Once it has ended, the terminal's output stays readable for
 * a few minutes, then the terminal is removed.
 */
running: boolean, 
/**
 * When it started.
 */
started: number, };
