// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a CLI's login proves who the person is.
 */
export type SignInMethod = "browser" | "device_code";
