// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Receipt } from "./Receipt.ts";

/**
 * One clause of a summary and the evidence for it.
 */
export type Span = { 
/**
 * Byte range in the summary text, on character boundaries. On the wire,
 * `{"start": …, "end": …}` in UTF-8 bytes.
 */
range: { start: number, end: number, }, 
/**
 * Evidence. Never empty.
 */
receipts: Array<Receipt>, };
