// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Engine } from "./Engine.ts";
import type { MemberId } from "./MemberId.ts";

/**
 * `POST /v1/workstreams/{id}/board-drafts`: start drafting, with what the preview showed.
 */
export type StartDraft = { 
/**
 * The agent to run: one of the caller's own. Default: the back office (`@office`).
 */
agent?: MemberId, 
/**
 * The CLI to run it in. Default: the agent's persona's, else Claude Code.
 */
engine?: Engine, 
/**
 * The [`DraftPreview::digest`] the person confirmed.
 */
digest: string, };
