// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SignInMethod } from "./SignInMethod.ts";

/**
 * `POST /v1/machines/{id}/agents/{engine}/sign-in`'s body, which may be omitted.
 */
export type StartSignIn = { 
/**
 * How to sign in; the CLI's default when absent.
 */
method?: SignInMethod, };
