// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Event } from "./Event.ts";

/**
 * Frames on `GET /v1/stream?since=<rev>`. `rev` is the hub's event revision. A client that
 * reconnects with `since` receives exactly what it missed.
 */
export type StreamFrame = { "type": "hello", 
/**
 * Current revision.
 */
rev: number, 
/**
 * Identifies this hub's event log; it is created with the store and never changes.
 * Revisions only mean something within one log: a client whose cached state came from
 * a different `log` must drop it and refetch.
 */
log: string, } | { "type": "events", 
/**
 * First revision in the batch.
 */
from_rev: number, 
/**
 * Last revision in the batch.
 */
to_rev: number, 
/**
 * The events, in order.
 */
events: Array<Event>, } | { "type": "ping", 
/**
 * Server time.
 */
at: number, };
