// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubtaskId } from "./SubtaskId.ts";
import type { SubtaskSource } from "./SubtaskSource.ts";

/**
 * One checklist line on a task.
 */
export type Subtask = { 
/**
 * Id.
 */
id: SubtaskId, 
/**
 * Text.
 */
text: string, 
/**
 * Whether it is done.
 */
done: boolean, 
/**
 * Origin.
 */
source: SubtaskSource, };
