// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemberId } from "./MemberId.ts";

/**
 * Where a subtask came from.
 */
export type SubtaskSource = { "kind": "human" } | { "kind": "agent_plan", 
/**
 * The agent whose plan this is.
 */
agent: MemberId, };
