// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkstreamSuggestion } from "./WorkstreamSuggestion.ts";

/**
 * A suggested project: a repository root (the nearest ancestor with a `.git`), or, for folders
 * with no `.git` above them, a folder shared by several of them. Never the person's home
 * directory, a scanned agent home, or a well-known system folder.
 */
export type Suggestion = { 
/**
 * Stable across a re-scan: the root's path.
 */
id: string, 
/**
 * Display name (the root folder's name).
 */
name: string, 
/**
 * The root folder.
 */
path: string, 
/**
 * Whether a `.git` was found at or above it (versus a grouped folder without one).
 */
is_git: boolean, 
/**
 * Sessions under it (any depth), excluding sub-agents.
 */
session_count: number, 
/**
 * Of those, in the last 30 days.
 */
recent_30d: number, 
/**
 * Of those, in the last 90 days.
 */
recent_90d: number, 
/**
 * Suggested workstreams inside it, ranked the same way as projects.
 */
workstreams: Array<WorkstreamSuggestion>, };
