// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Span } from "./Span.ts";

/**
 * Text whose every clause is a span with receipts.
 */
export type Summary = { 
/**
 * The prose.
 */
text: string, 
/**
 * Clauses of `text`, in order and not overlapping. Text outside spans is only punctuation
 * and spaces joining them.
 */
spans: Array<Span>, };
