// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A problem the last sync met.
 */
export type SyncProblem = { 
/**
 * A repository, a Jira project, or `""` for the whole integration.
 */
scope: string, 
/**
 * For people to read. Never holds a credential.
 */
message: string, };
