// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the last sync did.
 */
export type SyncCounts = { 
/**
 * Upstream changes read.
 */
changes: number, 
/**
 * Changes the hub applied (tasks created, updated or moved; workstreams shipped; notes).
 */
applied: number, 
/**
 * Conflicts raised as asks.
 */
conflicts: number, 
/**
 * Changes outside every linked scope, or about issues closed before they were first seen.
 */
skipped: number, 
/**
 * Upstream items or fields that were malformed and skipped.
 */
malformed: number, };
