// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncCounts } from "./SyncCounts.ts";
import type { SyncProblem } from "./SyncProblem.ts";

/**
 * Where an integration's sync stands.
 */
export type SyncStatus = { 
/**
 * A sync is under way.
 */
running: boolean, 
/**
 * When the last sync started.
 */
last_attempt_at?: number, 
/**
 * When the last sync that read every scope and applied what it found without a problem
 * ended: the "last sync" people see.
 */
last_success_at?: number, 
/**
 * When the next sync is due.
 */
next_at?: number, 
/**
 * Upstream asked the hub to wait until then.
 */
rate_limited_until?: number, 
/**
 * The last sync's problems.
 */
problems: Array<SyncProblem>, 
/**
 * What the last sync did.
 */
last_run?: SyncCounts, };
