// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Date } from "./Date.ts";
import type { ExternalRef } from "./ExternalRef.ts";
import type { MemberId } from "./MemberId.ts";
import type { Priority } from "./Priority.ts";
import type { ProjectId } from "./ProjectId.ts";
import type { Subtask } from "./Subtask.ts";
import type { TaskId } from "./TaskId.ts";
import type { TaskKey } from "./TaskKey.ts";
import type { TaskStatus } from "./TaskStatus.ts";
import type { WorkstreamId } from "./WorkstreamId.ts";

/**
 * A task: something a person or an agent finishes.
 */
export type Task = { 
/**
 * Id.
 */
id: TaskId, 
/**
 * People-facing key, e.g. `CMP-104`.
 */
key: TaskKey, 
/**
 * The project.
 */
project: ProjectId, 
/**
 * The workstream, if any. Small projects may have tasks without one.
 */
workstream?: WorkstreamId, 
/**
 * Title.
 */
title: string, 
/**
 * Description, which is also the brief an agent reads first.
 */
description: string, 
/**
 * Status.
 */
status: TaskStatus, 
/**
 * Priority.
 */
priority: Priority, 
/**
 * The assignee: a person or an agent.
 */
assignee?: MemberId, 
/**
 * Labels.
 */
labels: Array<string>, 
/**
 * Start date.
 */
start?: Date, 
/**
 * Due date.
 */
due?: Date, 
/**
 * Tasks that must finish first.
 */
blocked_by: Array<TaskId>, 
/**
 * The external item this task mirrors, such as a GitHub issue or a Jira issue.
 */
source?: ExternalRef, 
/**
 * Whether review can complete without a person (see [`Mover::BackOffice`]).
 */
accept_auto: boolean, 
/**
 * Checklist.
 */
subtasks: Array<Subtask>, };
