// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A people-facing task key, such as `CMP-104`. The number is unique within its project.
 */
export type TaskKey = string;
