// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Date } from "./Date.ts";
import type { Priority } from "./Priority.ts";
import type { TaskId } from "./TaskId.ts";
import type { WorkstreamId } from "./WorkstreamId.ts";

/**
 * A partial update of a [`Task`]: the body of `PATCH /v1/tasks/{id-or-key}`, and what a
 * `task_updated` event carries (there, only the fields that changed).
 *
 * A field left out is unchanged. `start`, `due` and `workstream` can also be cleared: JSON `null`
 * clears them, which is `Some(None)` here. On the other fields `null` counts as left out. Status,
 * assignee and subtasks change through their own routes and events.
 */
export type TaskPatch = { 
/**
 * New workstream; `Some(None)` takes the task out of its workstream.
 */
workstream?: WorkstreamId | null, 
/**
 * New title.
 */
title?: string, 
/**
 * New description.
 */
description?: string, 
/**
 * Archive or restore the task.
 */
archived?: boolean, 
/**
 * New priority.
 */
priority?: Priority, 
/**
 * New labels: the whole list.
 */
labels?: Array<string>, 
/**
 * New start date; `Some(None)` clears it.
 */
start?: Date | null, 
/**
 * New due date; `Some(None)` clears it.
 */
due?: Date | null, 
/**
 * New list of tasks that must finish first: the whole list.
 */
blocked_by?: Array<TaskId>, 
/**
 * New acceptance policy (see [`Mover::BackOffice`]).
 */
accept_auto?: boolean, };
