// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemberId } from "./MemberId.ts";

/**
 * Editable fields of a team; references are member ids, not persona ids.
 */
export type TeamEdit = { 
/**
 * Display name.
 */
name: string, 
/**
 * Lead, always included in members.
 */
lead: MemberId, 
/**
 * Existing people or agents.
 */
members: Array<MemberId>, };
