// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemberId } from "./MemberId.ts";
import type { TeamId } from "./TeamId.ts";

/**
 * A group of members with a lead, such as "Paper team".
 */
export type Team = { 
/**
 * Id.
 */
id: TeamId, 
/**
 * Name.
 */
name: string, 
/**
 * The lead member.
 */
lead: MemberId, 
/**
 * All members, including the lead.
 */
members: Array<MemberId>, };
