// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A terminal owned by a runner's runtime (a tmux window or a PTY).
 */
export type TerminalId = string;
