// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The two kinds of token (ADR-0006).
 */
export type TokenScope = "device" | "agent";
