// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionId } from "./SessionId.ts";

/**
 * The kinds of token (ADR-0006).
 */
export type TokenScope = "device" | "agent" | "reader" | { "session": SessionId };
