// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TranscriptItem } from "./TranscriptItem.ts";

/**
 * `GET /v1/sessions/{id}/transcript?before=<offset>&limit=<n>`: a page of items, oldest first.
 */
export type TranscriptPage = { 
/**
 * The items, oldest first.
 */
items: Array<TranscriptItem>, 
/**
 * Offset of the first record in this page. Pass it as `before` to get the previous page.
 */
from: number, 
/**
 * Offset just after the last record in this page.
 */
to: number, 
/**
 * True if this page starts at the beginning of the transcript.
 */
at_start: boolean, };
