// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlanItem } from "./PlanItem.ts";
import type { JsonValue } from "./serde_json/JsonValue.ts";

/**
 * One meaningful thing in a transcript. Every item carries the byte `offset` of its record, so it
 * can become a receipt.
 */
export type TranscriptItem = { "kind": "user_prompt", 
/**
 * Time.
 */
at: number, 
/**
 * Text.
 */
text: string, 
/**
 * Record offset.
 */
offset: number, } | { "kind": "assistant_text", 
/**
 * Time.
 */
at: number, 
/**
 * Text.
 */
text: string, 
/**
 * Record offset.
 */
offset: number, } | { "kind": "tool_use", 
/**
 * Time.
 */
at: number, 
/**
 * The CLI's id for the call, which pairs it with its result.
 */
call_id: string, 
/**
 * Tool name, e.g. `Bash`, `Edit`, `shell`.
 */
tool: string, 
/**
 * Short target, such as the command or path.
 */
target: string, 
/**
 * The raw input, for detail views. Large inputs are truncated by the adapter.
 */
input?: JsonValue, 
/**
 * Record offset.
 */
offset: number, } | { "kind": "tool_result", 
/**
 * Time.
 */
at: number, 
/**
 * The call it answers.
 */
call_id: string, 
/**
 * Whether it reported an error.
 */
is_error: boolean, 
/**
 * A short summary, e.g. the first lines of output.
 */
summary: string, 
/**
 * Record offset.
 */
offset: number, } | { "kind": "file_edit", 
/**
 * Time.
 */
at: number, 
/**
 * Path.
 */
path: string, 
/**
 * Lines added.
 */
added: number, 
/**
 * Lines removed.
 */
removed: number, 
/**
 * A unified diff, if the CLI recorded one.
 */
diff?: string, 
/**
 * Record offset.
 */
offset: number, } | { "kind": "plan_updated", 
/**
 * Time.
 */
at: number, 
/**
 * The full plan, in order.
 */
items: Array<PlanItem>, 
/**
 * Record offset.
 */
offset: number, } | { "kind": "question", 
/**
 * Time.
 */
at: number, 
/**
 * The question.
 */
text: string, 
/**
 * Options, if any.
 */
options: Array<string>, 
/**
 * Record offset.
 */
offset: number, } | { "kind": "turn_ended", 
/**
 * Time.
 */
at: number, 
/**
 * Record offset.
 */
offset: number, };
