// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where an answer stands.
 */
export type TurnState = "answering" | "answered" | "canceled" | "timed_out" | "too_long" | "failed";
