// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemberId } from "./MemberId.ts";
import type { WriteProposal } from "./WriteProposal.ts";
import type { WriteResult } from "./WriteResult.ts";
import type { WriteState } from "./WriteState.ts";

/**
 * A write, as `GET /v1/writes` shows it.
 */
export type UpstreamWrite = { 
/**
 * What it sends.
 */
proposal: WriteProposal, 
/**
 * Where it stands.
 */
state: WriteState, 
/**
 * How many times it was sent (each `write_started`).
 */
attempts: number, 
/**
 * When it was proposed.
 */
proposed_at: number, 
/**
 * When its ask was answered.
 */
answered_at?: number, 
/**
 * Who answered it.
 */
answered_by?: MemberId, 
/**
 * When its last attempt, or its denial, was recorded.
 */
finished_at?: number, 
/**
 * What came of it.
 */
result?: WriteResult, };
