// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An estimate of what the drafting agent uses, in tokens.
 */
export type UsageEstimate = { 
/**
 * What it reads: the prompt (a token for every 4 bytes, rounded up) and the agent CLI's own
 * instructions (a fixed allowance).
 */
input_tokens: number, 
/**
 * The most its answer may take: the proposal's bound (a token for every 4 bytes).
 */
output_tokens: number, };
