// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A workstream: one line of work inside a project.
 */
export type WorkstreamId = string;
