// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A workspace: one context such as "PhD research", hosted by one hub.
 */
export type WorkspaceId = string;
