// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Workspace default permission mode; skipping prompts is opt-in.
 */
export type WorkspacePermissionMode = "default" | "plan" | "accept-edits" | "bypass-permissions";
