// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A suggested workstream inside a [`Suggestion`]'s project: either an active sub-folder
 * (`branch` absent, named after the folder) or a non-default branch (`branch` set, named after
 * it). A project can suggest both kinds, and a session can count toward one of each.
 */
export type WorkstreamSuggestion = { 
/**
 * Stable within its project. For a sub-folder, the folder's own path (the project's `path`
 * joined with `name`, with the machine's separator): also where it is. For a branch,
 * `<project path>#<branch>`.
 */
id: string, 
/**
 * Display name: the folder's name, or the branch.
 */
name: string, 
/**
 * Set for a branch-based suggestion.
 */
branch?: string, 
/**
 * Sessions in it.
 */
session_count: number, 
/**
 * Of those, in the last 30 days.
 */
recent_30d: number, 
/**
 * Of those, in the last 90 days.
 */
recent_90d: number, };
