// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkstreamSuggestionKind } from "./WorkstreamSuggestionKind.ts";

/**
 * A suggested workstream inside a [`Suggestion`]'s project: the project's default workstream
 * (its root), a linked worktree, an active sub-folder of the main checkout (named after the
 * folder), or a non-default branch of the main checkout (`branch` set, named after it). A
 * session in a linked worktree counts toward that worktree only; one in the main checkout counts
 * toward the default workstream, and can count toward one sub-folder and one branch too.
 */
export type WorkstreamSuggestion = { 
/**
 * Stable within its project. For the default workstream, the project's `path`; for a
 * worktree, its folder; for a sub-folder, the folder's own path (the project's `path` joined
 * with `name`, with the machine's separator). Each of those is also where it is. For a
 * branch, `<project path>#<branch>`.
 */
id: string, 
/**
 * What it stands for.
 */
kind: WorkstreamSuggestionKind, 
/**
 * Display name: for the default workstream and a worktree, the branch checked out there
 * (else the folder's name, or `Main` for a folder without git); a sub-folder's name; or the
 * branch.
 */
name: string, 
/**
 * Set for a branch-based suggestion.
 */
branch?: string, 
/**
 * Sessions in it.
 */
session_count: number, 
/**
 * Of those, in the last 30 days.
 */
recent_30d: number, 
/**
 * Of those, in the last 90 days.
 */
recent_90d: number, };
