// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a [`WorkstreamSuggestion`] stands for.
 */
export type WorkstreamSuggestionKind = "main" | "worktree" | "folder" | "branch";
