// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalRef } from "./ExternalRef.ts";
import type { Health } from "./Health.ts";
import type { Location } from "./Location.ts";
import type { ProjectId } from "./ProjectId.ts";
import type { WorkstreamId } from "./WorkstreamId.ts";
import type { WorkstreamStatus } from "./WorkstreamStatus.ts";

/**
 * A workstream: one line of work inside a project, such as "Seed campaign".
 */
export type Workstream = { 
/**
 * Id.
 */
id: WorkstreamId, 
/**
 * The project it belongs to.
 */
project: ProjectId, 
/**
 * Name.
 */
name: string, 
/**
 * Status.
 */
status: WorkstreamStatus, 
/**
 * Health.
 */
health: Health, 
/**
 * Folders or branches whose sessions belong to this workstream.
 */
locations: Array<Location>, 
/**
 * Linked external items, such as a GitHub milestone or a Jira epic.
 */
external: Array<ExternalRef>, };
