// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileEncoding } from "./FileEncoding.ts";

/**
 * Replace a revision, or create exclusively with null revision.
 */
export type WriteFile = { 
/**
 * Required; null means the target must not exist. The custom deserializer keeps missing invalid.
 */
revision: string | null, 
/**
 * Encoding of content.
 */
encoding: FileEncoding, 
/**
 * New bytes.
 */
content: string, };
