// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AskId } from "./AskId.ts";
import type { EventId } from "./EventId.ts";
import type { ExternalRef } from "./ExternalRef.ts";
import type { ExternalSystem } from "./ExternalSystem.ts";
import type { IntegrationId } from "./IntegrationId.ts";
import type { MemberId } from "./MemberId.ts";
import type { TaskId } from "./TaskId.ts";
import type { WriteFields } from "./WriteFields.ts";
import type { WriteOperation } from "./WriteOperation.ts";

/**
 * A write waiting for, or past, a person's approval: exactly what will be sent
 * (`write_proposed`).
 */
export type WriteProposal = { 
/**
 * The approval ask; also the write's id.
 */
ask: AskId, 
/**
 * The integration it goes through.
 */
integration: IntegrationId, 
/**
 * GitHub or Jira.
 */
system: ExternalSystem, 
/**
 * The repository (`owner/repo`) or Jira project (`DEMO`) it writes to.
 */
scope: string, 
/**
 * The issue it changes; absent for `create_issue`.
 */
target?: ExternalRef, 
/**
 * The task it is about.
 */
task?: TaskId, 
/**
 * What it does.
 */
operation: WriteOperation, 
/**
 * Upstream's values of the fields it changes, as the last sync read them.
 */
before: WriteFields, 
/**
 * Exactly what is sent.
 */
after: WriteFields, 
/**
 * Whose change implied it, or who asked for it.
 */
requested_by: MemberId, 
/**
 * The event that implied it; absent when a person asked for it.
 */
cause?: EventId, };
