// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CloseReason } from "./CloseReason.ts";
import type { IssueState } from "./IssueState.ts";

/**
 * The fields of a write: what it sends (`after`), or upstream's values of the same fields
 * before it (`before`). Only the fields being changed are present. An `update` changes labels
 * with `add_labels` and `remove_labels`, never the whole list, so labels upstream has that the
 * hub does not hold are kept.
 */
export type WriteFields = { 
/**
 * Title (Jira: summary).
 */
title?: string, 
/**
 * Body (Jira: description).
 */
body?: string, 
/**
 * The whole label list: a new issue's (`create_issue`), or, in `before`, upstream's labels
 * as last read.
 */
labels?: Array<string>, 
/**
 * Labels an `update` adds.
 */
add_labels?: Array<string>, 
/**
 * Labels an `update` removes.
 */
remove_labels?: Array<string>, 
/**
 * GitHub: the milestone, as a link key (`owner/repo#milestone:2`).
 */
milestone?: string, 
/**
 * Jira: the epic's key (`DEMO-5`).
 */
epic?: string, 
/**
 * Open or closed.
 */
state?: IssueState, 
/**
 * Why it is closed (GitHub).
 */
close_reason?: CloseReason, 
/**
 * A comment's text.
 */
comment?: string, };
