// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a write stands.
 */
export type WriteState = "pending" | "approved" | "denied" | "sending" | "sent" | "failed" | "not_sent";
