// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalRef } from "./ExternalRef.ts";

/**
 * What came of one attempt, or of a write that was never sent (`write_finished`). On the wire,
 * tagged by `outcome`.
 */
export type WriteResult = { "outcome": "sent", 
/**
 * The issue a `create_issue` made; the task's `source` becomes it.
 */
created?: ExternalRef, 
/**
 * A link to what was written.
 */
url?: string, } | { "outcome": "failed", 
/**
 * For people to read: upstream's message (capped, without hidden characters) or why it
 * could not be reached. Never holds a credential.
 */
message: string, 
/**
 * Upstream's HTTP status, when it answered.
 */
status?: number, } | { "outcome": "not_sent", 
/**
 * Why, for people to read.
 */
reason: string, };
