//! Codex's `notify` setting, in `config.toml` (`CODEX_HOME`, else `~/.codex`).
//!
//! `notify` is a plain array of strings: the program and its fixed arguments; Codex appends the
//! JSON event as one more argument when it runs it. We want `notify = ["<exe>", "hook", "codex",
//! "notify"]`. Codex only honours `notify` in the user-level file, never a project's
//! `.codex/config.toml`, which is exactly the file this module edits.
//!
//! `toml_edit` keeps every comment and formatting choice in the rest of the file; we only ever
//! read or write the one `notify` key.
//!
//! If a *foreign* `notify` is already there, we never replace it: `install` reports the conflict
//! and makes no change, unless `--chain` is given, in which case we write a small wrapper script
//! that runs the existing command and then ours, and point `notify` at that instead. The
//! wrapper's own first lines record the original `notify` value as a comment, so `uninstall` can
//! restore it exactly and remove the wrapper.

use super::{Change, Plan, Status, Target};
use crate::config::Env;
use crate::error::{Error, Result};
use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use toml_edit::{Array, DocumentMut, Item};

const FILE_NAME: &str = "config.toml";

pub(crate) fn path(env: Env<'_>) -> Result<PathBuf> {
    Ok(super::config_dir(env, "CODEX_HOME", ".codex")?.join(FILE_NAME))
}

/// `notify`'s last three elements once we have written it; present regardless of the executable's
/// own (possibly stale, possibly chained-wrapper) path, so a moved binary is still recognised.
const MARKER_TAIL: [&str; 3] = ["hook", "codex", "notify"];

fn target_notify(exe: &str) -> Vec<String> {
    vec![exe.to_owned(), "hook".to_owned(), "codex".to_owned(), "notify".to_owned()]
}

fn is_ours(values: &[String]) -> bool {
    values.len() >= MARKER_TAIL.len() && values[values.len() - MARKER_TAIL.len()..] == MARKER_TAIL
}

fn as_strings(item: &Item) -> Option<Vec<String>> {
    item.as_array()?
        .iter()
        .map(|v| v.as_str().map(str::to_owned))
        .collect()
}

fn set_notify(doc: &mut DocumentMut, values: &[String]) {
    let mut array = Array::new();
    for v in values {
        array.push(v.as_str());
    }
    doc["notify"] = toml_edit::value(array);
}

const CHAIN_MARKER: &str = "Generated by `pitcrew hooks install --chain`";
const ORIGINAL_PREFIX: &str = "pitcrew-original-notify: ";

fn wrapper_file_name() -> &'static str {
    if cfg!(windows) {
        "pitcrew-notify-wrapper.cmd"
    } else {
        "pitcrew-notify-wrapper.sh"
    }
}

fn wrapper_path(config_path: &Path) -> PathBuf {
    config_path.with_file_name(wrapper_file_name())
}

/// A POSIX `sh` wrapper: the original command, then ours, both given the same arguments Codex
/// passed to the wrapper (just the JSON payload, as far as `notify` ever gives it any).
fn wrapper_script_unix(original: &[String], exe: &str) -> String {
    let mut out = String::from("#!/bin/sh\n");
    let _ = writeln!(out, "# {CHAIN_MARKER}. Safe to remove, or run: pitcrew hooks uninstall");
    let recorded = serde_json::to_string(original).unwrap_or_default();
    let _ = writeln!(out, "# {ORIGINAL_PREFIX}{recorded}");
    for part in original {
        let _ = write!(out, "{} ", super::shell_quote_unix(part));
    }
    out.push_str("\"$@\" >/dev/null 2>&1\n");
    let _ = writeln!(
        out,
        "{} hook codex notify \"$@\" >/dev/null 2>&1",
        super::shell_quote_unix(exe)
    );
    out.push_str("exit 0\n");
    out
}

/// The same, as a `cmd.exe` batch file (a plain `%*` forward of all arguments Codex passed is
/// enough; `notify` only ever gives it the one JSON argument).
fn wrapper_script_windows(original: &[String], exe: &str) -> String {
    let mut out = String::from("@echo off\n");
    let _ = writeln!(out, "rem {CHAIN_MARKER}. Safe to remove, or run: pitcrew hooks uninstall");
    let recorded = serde_json::to_string(original).unwrap_or_default();
    let _ = writeln!(out, "rem {ORIGINAL_PREFIX}{recorded}");
    for part in original {
        let _ = write!(out, "{} ", super::cmd_quote_windows(part));
    }
    out.push_str("%*\n");
    let _ = writeln!(out, "{} hook codex notify %*", super::cmd_quote_windows(exe));
    out.push_str("exit /b 0\n");
    out
}

fn wrapper_script(original: &[String], exe: &str) -> String {
    if cfg!(windows) {
        wrapper_script_windows(original, exe)
    } else {
        wrapper_script_unix(original, exe)
    }
}

fn is_our_wrapper(text: &[u8]) -> bool {
    String::from_utf8_lossy(text).contains(CHAIN_MARKER)
}

fn parse_recorded_original(text: &str) -> Option<Vec<String>> {
    text.lines().find_map(|line| {
        let idx = line.find(ORIGINAL_PREFIX)?;
        serde_json::from_str(&line[idx + ORIGINAL_PREFIX.len()..]).ok()
    })
}

fn parse(path: &Path, bytes: &[u8]) -> Result<DocumentMut> {
    let text = std::str::from_utf8(bytes)
        .map_err(|_| Error::invalid(format!("{} is not UTF-8 text", path.display())))?;
    text.parse::<DocumentMut>()
        .map_err(|e| Error::invalid(format!("{} is not valid TOML: {e}", path.display())))
}

pub(crate) fn plan_install(env: Env<'_>, exe: &str, chain: bool) -> Result<Plan> {
    let path = path(env)?;
    let before = super::read_optional(&path)?;
    let mut doc = match &before {
        Some(bytes) => parse(&path, bytes)?,
        None => DocumentMut::new(),
    };
    let target = target_notify(exe);
    let existing_item = doc.get("notify").cloned();
    let existing = existing_item.as_ref().and_then(as_strings);

    match existing_item {
        None => {
            set_notify(&mut doc, &target);
            Ok(Plan {
                target: Target::Codex,
                status: Status::Missing,
                detail: format!("{} (notify is not set)", path.display()),
                changes: vec![file_change(path, before, doc)],
            })
        }
        Some(_) if existing.is_none() => Ok(Plan {
            target: Target::Codex,
            status: Status::Conflicting,
            detail: format!(
                "{} has a notify that is not a plain array of strings; fix it by hand first",
                path.display()
            ),
            changes: vec![],
        }),
        Some(_) => {
            let existing = existing.unwrap_or_default();
            if existing == target {
                Ok(Plan {
                    target: Target::Codex,
                    status: Status::Installed,
                    detail: format!("{} (already set)", path.display()),
                    changes: vec![],
                })
            } else if is_ours(&existing) {
                set_notify(&mut doc, &target);
                Ok(Plan {
                    target: Target::Codex,
                    status: Status::Installed,
                    detail: format!("{} (updating the executable's path)", path.display()),
                    changes: vec![file_change(path, before, doc)],
                })
            } else if !chain {
                Ok(Plan {
                    target: Target::Codex,
                    status: Status::Conflicting,
                    detail: format!(
                        "{} already has notify = {existing:?}; rerun `install --chain` to run \
                         both, or remove it by hand",
                        path.display()
                    ),
                    changes: vec![],
                })
            } else {
                let wrapper_path = wrapper_path(&path);
                let wrapper_before = super::read_optional(&wrapper_path)?;
                let script = wrapper_script(&existing, exe);
                set_notify(&mut doc, &[wrapper_path.to_string_lossy().into_owned()]);
                Ok(Plan {
                    target: Target::Codex,
                    status: Status::Installed,
                    detail: format!(
                        "{} chained after the existing notify (wrapper at {})",
                        path.display(),
                        wrapper_path.display()
                    ),
                    changes: vec![
                        Change {
                            path: wrapper_path,
                            before: wrapper_before,
                            after: script.into_bytes(),
                            delete: false,
                            executable: true,
                        },
                        file_change(path, before, doc),
                    ],
                })
            }
        }
    }
}

fn file_change(path: PathBuf, before: Option<Vec<u8>>, doc: DocumentMut) -> Change {
    Change {
        path,
        before,
        after: doc.to_string().into_bytes(),
        delete: false,
        executable: false,
    }
}

pub(crate) fn plan_uninstall(env: Env<'_>) -> Result<Plan> {
    let path = path(env)?;
    let before = super::read_optional(&path)?;
    let Some(before_bytes) = &before else {
        return Ok(missing_plan(path));
    };
    let mut doc = parse(&path, before_bytes)?;
    let Some(existing) = doc.get("notify").and_then(as_strings) else {
        return Ok(missing_plan(path));
    };
    if !is_ours(&existing) {
        return Ok(missing_plan(path));
    }

    let wrapper_path = wrapper_path(&path);
    let wrapper_before = super::read_optional(&wrapper_path)?;
    let mut changes = Vec::new();
    match &wrapper_before {
        Some(bytes) if is_our_wrapper(bytes) => {
            let text = String::from_utf8_lossy(bytes);
            match parse_recorded_original(&text) {
                Some(original) => set_notify(&mut doc, &original),
                None => {
                    doc.as_table_mut().remove("notify");
                }
            }
            changes.push(Change {
                path: wrapper_path,
                before: wrapper_before,
                after: Vec::new(),
                delete: true,
                executable: false,
            });
        }
        _ => {
            doc.as_table_mut().remove("notify");
        }
    }
    changes.push(file_change(path.clone(), before, doc));
    Ok(Plan {
        target: Target::Codex,
        status: Status::Installed,
        detail: format!("{} (removing our notify hook)", path.display()),
        changes,
    })
}

fn missing_plan(path: PathBuf) -> Plan {
    Plan {
        target: Target::Codex,
        status: Status::Missing,
        detail: format!("{} (nothing of ours installed)", path.display()),
        changes: vec![],
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn env_of(pairs: &[(&str, &str)]) -> impl Fn(&str) -> Option<std::ffi::OsString> + use<> {
        let map: std::collections::HashMap<String, std::ffi::OsString> = pairs
            .iter()
            .map(|(k, v)| ((*k).to_owned(), std::ffi::OsString::from(v)))
            .collect();
        move |name| map.get(name).cloned()
    }

    const EXE: &str = "/home/sam/.local/bin/pitcrew";

    #[test]
    fn installs_then_is_a_no_op_then_uninstalls_cleanly() {
        let tmp = tempfile::tempdir().unwrap();
        let env = env_of(&[("CODEX_HOME", tmp.path().to_str().unwrap())]);
        let config_path = path(&env).unwrap();

        let plan = plan_install(&env, EXE, false).unwrap();
        assert!(plan.status == Status::Missing);
        let after = String::from_utf8(plan.changes[0].after.clone()).unwrap();
        std::fs::write(&config_path, &after).unwrap();

        let plan = plan_install(&env, EXE, false).unwrap();
        assert!(plan.status == Status::Installed);
        assert!(plan.changes.is_empty());

        let plan = plan_uninstall(&env).unwrap();
        let restored = String::from_utf8(plan.changes[0].after.clone()).unwrap();
        assert_eq!(restored.trim(), ""); // the file had nothing else in it
    }

    #[test]
    fn keeps_comments_and_unrelated_keys() {
        let original = "# a comment\napproval_policy = \"never\"\n";
        let tmp = tempfile::tempdir().unwrap();
        let config_path = tmp.path().join("config.toml");
        std::fs::write(&config_path, original).unwrap();
        let env = env_of(&[("CODEX_HOME", tmp.path().to_str().unwrap())]);

        let plan = plan_install(&env, EXE, false).unwrap();
        let after = String::from_utf8(plan.changes[0].after.clone()).unwrap();
        assert!(after.contains("# a comment"));
        assert!(after.contains("approval_policy = \"never\""));
        std::fs::write(&config_path, &after).unwrap();

        let plan = plan_uninstall(&env).unwrap();
        let restored = String::from_utf8(plan.changes[0].after.clone()).unwrap();
        assert_eq!(restored, original);
    }

    #[test]
    fn a_foreign_notify_is_reported_not_overwritten() {
        let original = r#"notify = ["terminal-notifier", "-title", "Codex"]"#;
        let tmp = tempfile::tempdir().unwrap();
        let config_path = tmp.path().join("config.toml");
        std::fs::write(&config_path, original).unwrap();
        let env = env_of(&[("CODEX_HOME", tmp.path().to_str().unwrap())]);

        let plan = plan_install(&env, EXE, false).unwrap();
        assert!(plan.status == Status::Conflicting);
        assert!(plan.changes.is_empty());
        // Untouched.
        assert_eq!(std::fs::read_to_string(&config_path).unwrap(), original);
    }

    #[test]
    fn chain_wraps_the_foreign_notify_and_uninstall_restores_it() {
        let original = r#"notify = ["terminal-notifier", "-title", "Codex"]"#;
        let tmp = tempfile::tempdir().unwrap();
        let config_path = tmp.path().join("config.toml");
        std::fs::write(&config_path, original).unwrap();
        let env = env_of(&[("CODEX_HOME", tmp.path().to_str().unwrap())]);

        let plan = plan_install(&env, EXE, true).unwrap();
        assert!(plan.status == Status::Installed);
        assert_eq!(plan.changes.len(), 2);
        for c in &plan.changes {
            std::fs::write(&c.path, &c.after).unwrap();
            if c.path != config_path {
                assert!(c.executable);
                let text = String::from_utf8_lossy(&c.after);
                assert!(text.contains("terminal-notifier"));
                assert!(text.contains(EXE));
            }
        }
        let now = std::fs::read_to_string(&config_path).unwrap();
        assert!(now.contains("pitcrew-notify-wrapper"));

        let plan = plan_uninstall(&env).unwrap();
        assert_eq!(plan.changes.len(), 2);
        for c in &plan.changes {
            if c.delete {
                assert!(c.path.to_string_lossy().contains("pitcrew-notify-wrapper"));
            } else {
                let restored = String::from_utf8(c.after.clone()).unwrap();
                assert_eq!(restored.trim(), original);
            }
        }
    }

    #[test]
    fn reinstalling_after_the_executable_moved_updates_the_path() {
        let tmp = tempfile::tempdir().unwrap();
        let env = env_of(&[("CODEX_HOME", tmp.path().to_str().unwrap())]);
        let config_path = path(&env).unwrap();
        let plan = plan_install(&env, "/old/pitcrew", false).unwrap();
        std::fs::write(&config_path, &plan.changes[0].after).unwrap();

        let plan = plan_install(&env, "/new/place/pitcrew", false).unwrap();
        assert!(plan.status == Status::Installed);
        let after = String::from_utf8(plan.changes[0].after.clone()).unwrap();
        assert!(after.contains("/new/place/pitcrew"));
        assert!(!after.contains("/old/pitcrew"));
    }
}
