//! Codex's `notify` setting, in `config.toml` (`CODEX_HOME`, else `~/.codex`).
//!
//! `notify` is a plain array of strings: the program and its fixed arguments; Codex appends the
//! JSON event as one more argument when it runs it. We want `notify = ["<exe>", "hook", "codex",
//! "notify"]`. Codex only honours `notify` in the user-level file, never a project's
//! `.codex/config.toml`, which is exactly the file this module edits.
//!
//! `toml_edit` keeps every comment and formatting choice in the rest of the file; we only ever
//! read or write the one `notify` key.
//!
//! If a *foreign* `notify` is already there, we never replace it: `install` reports the conflict
//! and makes no change, unless `--chain` is given, in which case we write a small wrapper script
//! that runs the existing command and then ours, and point `notify` at that instead.
//!
//! The original `notify` value's **exact source text** (comments, layout and all — not a value
//! reconstructed from parsed strings, which would lose them) is recorded in a sidecar JSON file
//! next to the wrapper, together with the plain values needed to build the wrapper's own
//! invocation line. Re-running `install` (with or without `--chain`) while already chained is
//! recognised and treated as idempotent — it refreshes the wrapper's embedded executable path if
//! that moved, never re-wraps an already-chained `notify` (which would otherwise have it call
//! itself forever) and never records a wrapper as "the original". `uninstall` restores the
//! recorded text byte-for-byte, writing the config change before deleting the wrapper and its
//! sidecar, so a failure partway through never leaves `notify` pointing at a file that is gone.
//! An unreadable record is reported as a conflict, never silently dropped.

use super::{Change, Plan, Status, Target};
use crate::config::Env;
use crate::error::{Error, Result};
use serde::{Deserialize, Serialize};
use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use toml_edit::{Array, DocumentMut, Item};

const FILE_NAME: &str = "config.toml";

pub(crate) fn path(env: Env<'_>) -> Result<PathBuf> {
    Ok(super::config_dir(env, "CODEX_HOME", ".codex")?.join(FILE_NAME))
}

/// `notify`'s last three elements once we have written it; present regardless of the executable's
/// own (possibly stale) path, so a moved binary is still recognised.
const MARKER_TAIL: [&str; 3] = ["hook", "codex", "notify"];

fn target_notify(exe: &str) -> Vec<String> {
    vec![
        exe.to_owned(),
        "hook".to_owned(),
        "codex".to_owned(),
        "notify".to_owned(),
    ]
}

/// Whether `values` is a direct (non-chained) install of ours.
fn is_ours(values: &[String]) -> bool {
    values.len() >= MARKER_TAIL.len() && values[values.len() - MARKER_TAIL.len()..] == MARKER_TAIL
}

fn as_strings(item: &Item) -> Option<Vec<String>> {
    item.as_array()?
        .iter()
        .map(|v| v.as_str().map(str::to_owned))
        .collect()
}

fn set_notify(doc: &mut DocumentMut, values: &[String]) {
    let mut array = Array::new();
    for v in values {
        array.push(v.as_str());
    }
    doc["notify"] = toml_edit::value(array);
}

const CHAIN_MARKER: &str = "Generated by `pitcrew hooks install --chain`";

fn wrapper_file_name() -> &'static str {
    if cfg!(windows) {
        "pitcrew-notify-wrapper.cmd"
    } else {
        "pitcrew-notify-wrapper.sh"
    }
}

fn wrapper_path(config_path: &Path) -> PathBuf {
    config_path.with_file_name(wrapper_file_name())
}

fn sidecar_path(config_path: &Path) -> PathBuf {
    config_path.with_file_name("pitcrew-notify-original.json")
}

/// The chain's recorded state: `values`, the original `notify`'s plain string values (used to
/// build the wrapper's invocation line, since that cannot embed TOML syntax or comments), and
/// `toml`, the original `notify` value's **exact source text** — comments, multi-line layout and
/// all — restored verbatim on `uninstall` rather than ever being reconstructed from `values`.
#[derive(Serialize, Deserialize)]
struct OriginalRecord {
    values: Vec<String>,
    toml: String,
}

fn sidecar_json(values: &[String], toml_text: &str) -> String {
    let record = OriginalRecord {
        values: values.to_vec(),
        toml: toml_text.to_owned(),
    };
    serde_json::to_string_pretty(&record).unwrap_or_default()
}

fn parse_sidecar(bytes: &[u8]) -> Option<OriginalRecord> {
    serde_json::from_slice(bytes).ok()
}

/// Whether `program`'s file extension means it must be invoked with `call` from a batch file —
/// otherwise control never returns to run our own notify afterward (a plain batch-to-batch
/// invocation is a `goto`, not a call).
fn needs_call_prefix(program: &str) -> bool {
    let lower = program.to_ascii_lowercase();
    lower.ends_with(".bat") || lower.ends_with(".cmd")
}

/// A POSIX `sh` wrapper: the original command, then ours, both given the same arguments Codex
/// passed to the wrapper (just the JSON payload, as far as `notify` ever gives it any).
fn wrapper_script_unix(original: &[String], exe: &str) -> String {
    let mut out = String::from("#!/bin/sh\n");
    let _ = writeln!(
        out,
        "# {CHAIN_MARKER}. Safe to remove, or run: pitcrew hooks uninstall"
    );
    for part in original {
        let _ = write!(out, "{} ", super::shell_quote_unix(part));
    }
    out.push_str("\"$@\" >/dev/null 2>&1\n");
    let _ = writeln!(
        out,
        "{} hook codex notify \"$@\" >/dev/null 2>&1",
        super::shell_quote_unix(exe)
    );
    out.push_str("exit 0\n");
    out
}

/// The same, as a `cmd.exe` batch file (a plain `%*` forward of all arguments Codex passed is
/// enough; `notify` only ever gives it the one JSON argument). `cmd_quote_windows` already
/// doubles any literal `%` and quotes `cmd.exe`'s other metacharacters.
fn wrapper_script_windows(original: &[String], exe: &str) -> String {
    let mut out = String::from("@echo off\n");
    let _ = writeln!(
        out,
        "rem {CHAIN_MARKER}. Safe to remove, or run: pitcrew hooks uninstall"
    );
    if original.first().is_some_and(|p| needs_call_prefix(p)) {
        out.push_str("call ");
    }
    for part in original {
        let _ = write!(out, "{} ", super::cmd_quote_windows(part));
    }
    out.push_str("%*\n");
    let _ = writeln!(
        out,
        "{} hook codex notify %*",
        super::cmd_quote_windows(exe)
    );
    out.push_str("exit /b 0\n");
    out
}

fn wrapper_script(original: &[String], exe: &str) -> String {
    if cfg!(windows) {
        wrapper_script_windows(original, exe)
    } else {
        wrapper_script_unix(original, exe)
    }
}

fn is_our_wrapper(text: &[u8]) -> bool {
    String::from_utf8_lossy(text).contains(CHAIN_MARKER)
}

fn parse(path: &Path, bytes: &[u8]) -> Result<DocumentMut> {
    let text = std::str::from_utf8(bytes)
        .map_err(|_| Error::invalid(format!("{} is not UTF-8 text", path.display())))?;
    text.parse::<DocumentMut>()
        .map_err(|e| Error::invalid(format!("{} is not valid TOML: {e}", path.display())))
}

/// Parses `value_text` (the exact source text of a `notify` value, as recorded) back into an
/// `Item` carrying that same formatting, by wrapping it in a one-line `notify = …` document and
/// pulling the key back out — `toml_edit` reproduces an unmodified parsed item's own formatting
/// exactly, so this is the verbatim original, not a reconstruction.
fn parse_notify_value(value_text: &str) -> Result<Item> {
    // No space between `=` and `{value_text}`: `value_text` is `Item::to_string()`, which already
    // includes that value's own leading decor (the space that followed the original `=`) — adding
    // another here would double it (`notify =  […]`) and break the byte-exact restoration this
    // exists for.
    let snippet = format!("notify ={value_text}\n");
    let mut doc: DocumentMut = snippet
        .parse()
        .map_err(|e| Error::internal(format!("cannot restore the original notify ({e})")))?;
    doc.remove("notify")
        .ok_or_else(|| Error::internal("cannot restore the original notify (internal error)"))
}

/// `toml_edit`'s printer does not reliably keep a document's original line-ending style or a
/// missing final newline once anything in it is re-serialised (observed directly: CRLF comes
/// back as LF, and a file with no trailing newline gets one) — so both are restored here to match
/// `before`, after asking `toml_edit` to print the rest.
fn match_line_endings(generated: String, before: Option<&[u8]>) -> String {
    let Some(before) = before else {
        return generated;
    };
    let original = String::from_utf8_lossy(before);
    let had_crlf = original.contains("\r\n");
    let had_trailing_newline = original.ends_with('\n');

    let mut out = generated.replace("\r\n", "\n");
    if had_crlf {
        out = out.replace('\n', "\r\n");
    }
    if had_trailing_newline && !out.ends_with('\n') {
        out.push('\n');
    } else if !had_trailing_newline && out.ends_with('\n') {
        out.pop();
        if out.ends_with('\r') {
            out.pop();
        }
    }
    out
}

fn file_change(path: PathBuf, before: Option<Vec<u8>>, doc: DocumentMut) -> Change {
    let after = match_line_endings(doc.to_string(), before.as_deref());
    Change {
        path,
        before,
        after: after.into_bytes(),
        delete: false,
        executable: false,
    }
}

fn conflicting(path: &Path, detail: impl std::fmt::Display) -> Plan {
    Plan {
        target: Target::Codex,
        status: Status::Conflicting,
        detail: format!("{}: {detail}", path.display()),
        changes: vec![],
    }
}

/// Whether `notify` currently names exactly our wrapper's own path (regardless of whether the
/// wrapper file itself still backs that up — callers check that separately).
fn points_at_our_wrapper(values: &[String], wrapper_path: &Path) -> bool {
    values.len() == 1 && values[0] == wrapper_path.to_string_lossy()
}

pub(crate) fn plan_install(env: Env<'_>, exe: &str, chain: bool) -> Result<Plan> {
    let path = path(env)?;
    let before = super::read_optional(&path)?;
    let mut doc = match &before {
        Some(bytes) => parse(&path, bytes)?,
        None => DocumentMut::new(),
    };
    let target = target_notify(exe);
    let existing_item = doc.get("notify").cloned();
    let existing = existing_item.as_ref().and_then(as_strings);
    let wrapper_path = wrapper_path(&path);

    // Already chained: refresh the wrapper's embedded executable path if it moved, never
    // re-wrap it (that would make `notify` call itself forever), and never require `--chain`
    // again just to keep an existing chain in good repair.
    if let Some(values) = &existing
        && points_at_our_wrapper(values, &wrapper_path)
    {
        let wrapper_before = super::read_optional(&wrapper_path)?;
        let Some(wrapper_bytes) = &wrapper_before else {
            return Ok(conflicting(
                &path,
                format!(
                    "notify points at {}, which does not exist; fix it by hand first",
                    wrapper_path.display()
                ),
            ));
        };
        if !is_our_wrapper(wrapper_bytes) {
            return Ok(conflicting(
                &path,
                format!(
                    "notify points at {}, which was not written by pitcrew; fix it by hand first",
                    wrapper_path.display()
                ),
            ));
        }
        let sidecar_path = sidecar_path(&path);
        let sidecar_before = super::read_optional(&sidecar_path)?;
        let Some(record) = sidecar_before.as_deref().and_then(parse_sidecar) else {
            return Ok(conflicting(
                &path,
                format!(
                    "the chain's recorded original notify ({}) is missing or unreadable; fix it \
                     by hand first",
                    sidecar_path.display()
                ),
            ));
        };
        let new_script = wrapper_script(&record.values, exe);
        if new_script.as_bytes() == wrapper_bytes.as_slice() {
            return Ok(Plan {
                target: Target::Codex,
                status: Status::Installed,
                detail: format!("{} (already chained)", path.display()),
                changes: vec![],
            });
        }
        return Ok(Plan {
            target: Target::Codex,
            status: Status::Installed,
            detail: format!(
                "{} (chained; updating the executable's path in the wrapper)",
                path.display()
            ),
            changes: vec![Change {
                path: wrapper_path,
                before: wrapper_before,
                after: new_script.into_bytes(),
                delete: false,
                executable: true,
            }],
        });
    }

    match existing_item {
        None => {
            set_notify(&mut doc, &target);
            Ok(Plan {
                target: Target::Codex,
                status: Status::Missing,
                detail: format!("{} (notify is not set)", path.display()),
                changes: vec![file_change(path, before, doc)],
            })
        }
        Some(_) if existing.is_none() => Ok(conflicting(
            &path,
            "has a notify that is not a plain array of strings; fix it by hand first",
        )),
        Some(ref item) => {
            let existing = existing.unwrap_or_default();
            if existing == target {
                Ok(Plan {
                    target: Target::Codex,
                    status: Status::Installed,
                    detail: format!("{} (already set)", path.display()),
                    changes: vec![],
                })
            } else if is_ours(&existing) {
                set_notify(&mut doc, &target);
                Ok(Plan {
                    target: Target::Codex,
                    status: Status::Installed,
                    detail: format!("{} (updating the executable's path)", path.display()),
                    changes: vec![file_change(path, before, doc)],
                })
            } else if !chain {
                Ok(conflicting(
                    &path,
                    format!(
                        "already has notify = {existing:?}; rerun `install --chain` to run \
                         both, or remove it by hand"
                    ),
                ))
            } else {
                let wrapper_before = super::read_optional(&wrapper_path)?;
                if let Some(bytes) = &wrapper_before
                    && !is_our_wrapper(bytes)
                {
                    return Ok(conflicting(
                        &path,
                        format!(
                            "{} already exists and was not written by pitcrew; move it aside \
                             first",
                            wrapper_path.display()
                        ),
                    ));
                }
                let original_text = item.to_string();
                let script = wrapper_script(&existing, exe);
                let sidecar_path = sidecar_path(&path);
                let sidecar_before = super::read_optional(&sidecar_path)?;
                let sidecar = sidecar_json(&existing, &original_text);
                set_notify(&mut doc, &[wrapper_path.to_string_lossy().into_owned()]);
                Ok(Plan {
                    target: Target::Codex,
                    status: Status::Installed,
                    detail: format!(
                        "{} chained after the existing notify (wrapper at {})",
                        path.display(),
                        wrapper_path.display()
                    ),
                    changes: vec![
                        Change {
                            path: wrapper_path,
                            before: wrapper_before,
                            after: script.into_bytes(),
                            delete: false,
                            executable: true,
                        },
                        Change {
                            path: sidecar_path,
                            before: sidecar_before,
                            after: sidecar.into_bytes(),
                            delete: false,
                            executable: false,
                        },
                        file_change(path, before, doc),
                    ],
                })
            }
        }
    }
}

pub(crate) fn plan_uninstall(env: Env<'_>) -> Result<Plan> {
    let path = path(env)?;
    let before = super::read_optional(&path)?;
    let Some(before_bytes) = &before else {
        return Ok(missing_plan(path));
    };
    let mut doc = parse(&path, before_bytes)?;
    let Some(existing) = doc.get("notify").and_then(as_strings) else {
        return Ok(missing_plan(path));
    };

    let wrapper_path = wrapper_path(&path);
    if points_at_our_wrapper(&existing, &wrapper_path) {
        let wrapper_before = super::read_optional(&wrapper_path)?;
        let Some(wrapper_bytes) = &wrapper_before else {
            return Ok(conflicting(
                &path,
                format!(
                    "notify points at {}, which does not exist; fix it by hand first",
                    wrapper_path.display()
                ),
            ));
        };
        if !is_our_wrapper(wrapper_bytes) {
            return Ok(conflicting(
                &path,
                format!(
                    "notify points at {}, which was not written by pitcrew; fix it by hand first",
                    wrapper_path.display()
                ),
            ));
        }
        let sidecar_path = sidecar_path(&path);
        let sidecar_before = super::read_optional(&sidecar_path)?;
        let Some(record) = sidecar_before.as_deref().and_then(parse_sidecar) else {
            return Ok(conflicting(
                &path,
                format!(
                    "the chain's recorded original notify ({}) is missing or unreadable; \
                     notify was left pointing at the wrapper so nothing is lost — fix it by \
                     hand first",
                    sidecar_path.display()
                ),
            ));
        };
        let restored = match parse_notify_value(&record.toml) {
            Ok(item) => item,
            Err(e) => return Ok(conflicting(&path, e.message)),
        };
        doc["notify"] = restored;
        // The config is restored *first*: if anything fails before the wrapper and sidecar are
        // deleted, `notify` already points at the real original again, never at a file we are
        // about to remove.
        let changes = vec![
            file_change(path.clone(), before, doc),
            Change {
                path: wrapper_path,
                before: wrapper_before,
                after: Vec::new(),
                delete: true,
                executable: false,
            },
            Change {
                path: sidecar_path,
                before: sidecar_before,
                after: Vec::new(),
                delete: true,
                executable: false,
            },
        ];
        return Ok(Plan {
            target: Target::Codex,
            status: Status::Installed,
            detail: format!(
                "{} (removing the chain; restoring the original notify)",
                path.display()
            ),
            changes,
        });
    }

    if !is_ours(&existing) {
        return Ok(missing_plan(path));
    }
    doc.as_table_mut().remove("notify");
    Ok(Plan {
        target: Target::Codex,
        status: Status::Installed,
        detail: format!("{} (removing our notify hook)", path.display()),
        changes: vec![file_change(path, before, doc)],
    })
}

fn missing_plan(path: PathBuf) -> Plan {
    Plan {
        target: Target::Codex,
        status: Status::Missing,
        detail: format!("{} (nothing of ours installed)", path.display()),
        changes: vec![],
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn env_of(pairs: &[(&str, &str)]) -> impl Fn(&str) -> Option<std::ffi::OsString> + use<> {
        let map: std::collections::HashMap<String, std::ffi::OsString> = pairs
            .iter()
            .map(|(k, v)| ((*k).to_owned(), std::ffi::OsString::from(v)))
            .collect();
        move |name| map.get(name).cloned()
    }

    const EXE: &str = "/home/sam/.local/bin/pitcrew";

    #[test]
    fn installs_then_is_a_no_op_then_uninstalls_cleanly() {
        let tmp = tempfile::tempdir().unwrap();
        let env = env_of(&[("CODEX_HOME", tmp.path().to_str().unwrap())]);
        let config_path = path(&env).unwrap();

        let plan = plan_install(&env, EXE, false).unwrap();
        assert!(plan.status == Status::Missing);
        let after = String::from_utf8(plan.changes[0].after.clone()).unwrap();
        std::fs::write(&config_path, &after).unwrap();

        let plan = plan_install(&env, EXE, false).unwrap();
        assert!(plan.status == Status::Installed);
        assert!(plan.changes.is_empty());

        let plan = plan_uninstall(&env).unwrap();
        let restored = String::from_utf8(plan.changes[0].after.clone()).unwrap();
        assert_eq!(restored.trim(), ""); // the file had nothing else in it
    }

    #[test]
    fn keeps_comments_and_unrelated_keys() {
        let original = "# a comment\napproval_policy = \"never\"\n";
        let tmp = tempfile::tempdir().unwrap();
        let config_path = tmp.path().join("config.toml");
        std::fs::write(&config_path, original).unwrap();
        let env = env_of(&[("CODEX_HOME", tmp.path().to_str().unwrap())]);

        let plan = plan_install(&env, EXE, false).unwrap();
        let after = String::from_utf8(plan.changes[0].after.clone()).unwrap();
        assert!(after.contains("# a comment"));
        assert!(after.contains("approval_policy = \"never\""));
        std::fs::write(&config_path, &after).unwrap();

        let plan = plan_uninstall(&env).unwrap();
        let restored = String::from_utf8(plan.changes[0].after.clone()).unwrap();
        assert_eq!(restored, original);
    }

    #[test]
    fn a_foreign_notify_is_reported_not_overwritten() {
        let original = r#"notify = ["terminal-notifier", "-title", "Codex"]"#;
        let tmp = tempfile::tempdir().unwrap();
        let config_path = tmp.path().join("config.toml");
        std::fs::write(&config_path, original).unwrap();
        let env = env_of(&[("CODEX_HOME", tmp.path().to_str().unwrap())]);

        let plan = plan_install(&env, EXE, false).unwrap();
        assert!(plan.status == Status::Conflicting);
        assert!(plan.changes.is_empty());
        // Untouched.
        assert_eq!(std::fs::read_to_string(&config_path).unwrap(), original);
    }

    /// Applies every change in `plan` (test helper, mirroring `install::apply_change` closely
    /// enough for these tests, without pulling in the re-check-before-write machinery).
    fn apply(plan: &Plan) {
        for c in &plan.changes {
            if c.delete {
                let _ = std::fs::remove_file(&c.path);
            } else {
                std::fs::write(&c.path, &c.after).unwrap();
            }
        }
    }

    #[test]
    fn chain_wraps_the_foreign_notify_and_uninstall_restores_it_byte_exact() {
        let original = "notify = [\"terminal-notifier\", \"-title\", \"Codex\"] # a comment\n";
        let tmp = tempfile::tempdir().unwrap();
        let config_path = tmp.path().join("config.toml");
        std::fs::write(&config_path, original).unwrap();
        let env = env_of(&[("CODEX_HOME", tmp.path().to_str().unwrap())]);

        let plan = plan_install(&env, EXE, true).unwrap();
        assert!(plan.status == Status::Installed);
        assert_eq!(plan.changes.len(), 3);
        for c in &plan.changes {
            if c.path != config_path {
                assert!(c.path.to_string_lossy().contains("pitcrew-notify"));
            }
        }
        apply(&plan);
        let now = std::fs::read_to_string(&config_path).unwrap();
        assert!(now.contains("pitcrew-notify-wrapper"));

        let plan = plan_uninstall(&env).unwrap();
        assert_eq!(plan.changes.len(), 3);
        // The config change comes first: restoring it never depends on the wrapper or sidecar
        // still existing.
        assert_eq!(plan.changes[0].path, config_path);
        assert!(!plan.changes[0].delete);
        let restored = String::from_utf8(plan.changes[0].after.clone()).unwrap();
        assert_eq!(
            restored, original,
            "must be byte-exact, including the trailing comment"
        );
        for c in &plan.changes[1..] {
            assert!(c.delete);
        }
    }

    #[test]
    fn chain_twice_is_idempotent_and_never_wraps_the_wrapper() {
        let original = r#"notify = ["terminal-notifier", "-title", "Codex"]"#;
        let tmp = tempfile::tempdir().unwrap();
        let config_path = tmp.path().join("config.toml");
        std::fs::write(&config_path, original).unwrap();
        let env = env_of(&[("CODEX_HOME", tmp.path().to_str().unwrap())]);

        let plan = plan_install(&env, EXE, true).unwrap();
        apply(&plan);
        let after_first = std::fs::read_to_string(&config_path).unwrap();

        // Running `install --chain` again, unchanged, is a complete no-op.
        let plan = plan_install(&env, EXE, true).unwrap();
        assert!(plan.status == Status::Installed, "{}", plan.detail);
        assert!(
            plan.changes.is_empty(),
            "must not re-wrap an already-chained notify"
        );
        assert_eq!(std::fs::read_to_string(&config_path).unwrap(), after_first);

        // Running plain `install` (no --chain) while already chained is also a no-op, not a
        // conflict demanding `--chain` again.
        let plan = plan_install(&env, EXE, false).unwrap();
        assert!(plan.status == Status::Installed, "{}", plan.detail);
        assert!(plan.changes.is_empty());

        // And uninstall still restores the one true original, not the wrapper.
        let plan = plan_uninstall(&env).unwrap();
        let restored = String::from_utf8(plan.changes[0].after.clone()).unwrap();
        assert_eq!(restored.trim(), original);
    }

    #[test]
    fn chain_then_moved_executable_updates_the_wrapper_only() {
        let original = r#"notify = ["terminal-notifier"]"#;
        let tmp = tempfile::tempdir().unwrap();
        let config_path = tmp.path().join("config.toml");
        std::fs::write(&config_path, original).unwrap();
        let env = env_of(&[("CODEX_HOME", tmp.path().to_str().unwrap())]);

        let plan = plan_install(&env, "/old/place/pitcrew", true).unwrap();
        apply(&plan);
        let config_after_chain = std::fs::read_to_string(&config_path).unwrap();

        let plan = plan_install(&env, "/new/place/pitcrew", true).unwrap();
        assert!(plan.status == Status::Installed);
        assert_eq!(plan.changes.len(), 1, "only the wrapper needs to change");
        let wrapper_path = &plan.changes[0].path;
        assert!(
            wrapper_path
                .to_string_lossy()
                .contains("pitcrew-notify-wrapper")
        );
        let new_script = String::from_utf8(plan.changes[0].after.clone()).unwrap();
        assert!(new_script.contains("/new/place/pitcrew"));
        assert!(!new_script.contains("/old/place/pitcrew"));
        apply(&plan);
        // The config itself (notify still pointing at the wrapper) never changed.
        assert_eq!(
            std::fs::read_to_string(&config_path).unwrap(),
            config_after_chain
        );

        let plan = plan_uninstall(&env).unwrap();
        let restored = String::from_utf8(plan.changes[0].after.clone()).unwrap();
        assert_eq!(restored.trim(), original);
    }

    #[test]
    fn install_refuses_to_overwrite_an_unrelated_wrapper_file() {
        let original = r#"notify = ["terminal-notifier"]"#;
        let tmp = tempfile::tempdir().unwrap();
        let config_path = tmp.path().join("config.toml");
        std::fs::write(&config_path, original).unwrap();
        std::fs::write(
            tmp.path().join("pitcrew-notify-wrapper.sh"),
            "#!/bin/sh\necho mine\n",
        )
        .unwrap();
        let env = env_of(&[("CODEX_HOME", tmp.path().to_str().unwrap())]);

        let plan = plan_install(&env, EXE, true).unwrap();
        assert!(plan.status == Status::Conflicting);
        assert!(plan.changes.is_empty());
        assert_eq!(
            std::fs::read_to_string(tmp.path().join("pitcrew-notify-wrapper.sh")).unwrap(),
            "#!/bin/sh\necho mine\n"
        );
    }

    #[test]
    fn uninstall_with_a_missing_sidecar_is_a_conflict_not_a_removal() {
        let original = r#"notify = ["terminal-notifier"]"#;
        let tmp = tempfile::tempdir().unwrap();
        let config_path = tmp.path().join("config.toml");
        std::fs::write(&config_path, original).unwrap();
        let env = env_of(&[("CODEX_HOME", tmp.path().to_str().unwrap())]);

        let plan = plan_install(&env, EXE, true).unwrap();
        apply(&plan);
        // Someone deletes the sidecar by hand, but leaves the wrapper and the config pointing at
        // it.
        let sidecar = tmp.path().join("pitcrew-notify-original.json");
        std::fs::remove_file(&sidecar).unwrap();

        let plan = plan_uninstall(&env).unwrap();
        assert!(plan.status == Status::Conflicting, "{}", plan.detail);
        assert!(plan.changes.is_empty());
        // notify is left exactly as it was — still pointing at the wrapper, not silently
        // cleared.
        assert!(
            std::fs::read_to_string(&config_path)
                .unwrap()
                .contains("pitcrew-notify-wrapper")
        );
    }

    #[test]
    fn reinstalling_after_the_executable_moved_updates_the_path() {
        let tmp = tempfile::tempdir().unwrap();
        let env = env_of(&[("CODEX_HOME", tmp.path().to_str().unwrap())]);
        let config_path = path(&env).unwrap();
        let plan = plan_install(&env, "/old/pitcrew", false).unwrap();
        std::fs::write(&config_path, &plan.changes[0].after).unwrap();

        let plan = plan_install(&env, "/new/place/pitcrew", false).unwrap();
        assert!(plan.status == Status::Installed);
        let after = String::from_utf8(plan.changes[0].after.clone()).unwrap();
        assert!(after.contains("/new/place/pitcrew"));
        assert!(!after.contains("/old/pitcrew"));
    }

    #[test]
    fn windows_wrapper_doubles_percent_and_calls_a_bat_original() {
        let original = vec!["C:\\tools\\notify.bat".to_owned(), "50% done".to_owned()];
        let script = wrapper_script_windows(&original, "C:\\pitcrew\\pitcrew.exe");
        assert!(script.contains("call "), "{script}");
        assert!(script.contains("50%% done"), "{script}");
        assert!(
            !script.contains("notify.bat\" \"50% done"),
            "unescaped %: {script}"
        );
    }

    #[test]
    fn windows_wrapper_quotes_cmd_metacharacters_in_arguments() {
        let original = vec!["C:\\tools\\notify.exe".to_owned(), "a&b".to_owned()];
        let script = wrapper_script_windows(&original, "C:\\pitcrew\\pitcrew.exe");
        assert!(script.contains("\"a&b\""), "{script}");
    }

    #[test]
    fn crlf_and_a_missing_final_newline_round_trip() {
        let original = "notify = [\"terminal-notifier\"]\r\napproval_policy = \"never\"";
        let tmp = tempfile::tempdir().unwrap();
        let config_path = tmp.path().join("config.toml");
        std::fs::write(&config_path, original).unwrap();
        let env = env_of(&[("CODEX_HOME", tmp.path().to_str().unwrap())]);

        let plan = plan_install(&env, EXE, true).unwrap();
        apply(&plan);
        let plan = plan_uninstall(&env).unwrap();
        let restored = String::from_utf8(plan.changes[0].after.clone()).unwrap();
        assert_eq!(
            restored, original,
            "CRLF and the missing final newline must survive"
        );
    }
}
