//! OpenCode's plugin auto-discovery: any `*.js`/`*.ts` file in `<config dir>/plugin/` is loaded
//! and run in-process, with no config-file entry needed. OpenCode resolves its config directory
//! the same way `XDG_CONFIG_HOME` is resolved anywhere else: that variable if set, else
//! `<home>/.config`, then `/opencode` — confirmed against the installed `opencode` binary's own
//! path-resolution code and its bundled documentation (there is no separate `OPENCODE_CONFIG_DIR`
//! or similar to opt out of this with; tests use `XDG_CONFIG_HOME`, which is also what a real
//! OpenCode install honours).
//!
//! Unlike Claude Code and Codex, there is nothing to merge: we own one whole file,
//! `plugin/pitcrew.js`, marked by a comment at its top. `install` writes it (or refreshes it if
//! our own content has changed, e.g. the executable moved); `uninstall` removes it if, and only
//! if, that marker is still there. A file already at that path without our marker is left alone
//! and reported as a conflict — pick a different plugin file name is the only other auto-wired-in
//! option OpenCode gives us, so we leave the choice to the person.
//!
//! The plugin itself just forwards every OpenCode bus event to `pitcrew hook opencode <event>`,
//! fire-and-forget. Its own runtime behaviour beyond making that one call is out of scope here
//! (see `docs/build/briefs/I-hook-install.md`); the event name is rewritten from OpenCode's
//! dotted form (`session.idle`) to the daemon's allowed charset (`session_idle`).

use super::{Change, Plan, Status, Target};
use crate::config::Env;
use crate::error::{Error, Result};
use std::path::PathBuf;

const MARKER: &str = "// Generated by `pitcrew hooks install`.";

pub(crate) fn plugin_dir(env: Env<'_>) -> Result<PathBuf> {
    let config_home = match super::env_str(env, "XDG_CONFIG_HOME") {
        Some(v) => PathBuf::from(v),
        None => super::user_home(env)
            .ok_or_else(|| Error::invalid("cannot find the home directory (set HOME)"))?
            .join(".config"),
    };
    Ok(config_home.join("opencode").join("plugin"))
}

pub(crate) fn path(env: Env<'_>) -> Result<PathBuf> {
    Ok(plugin_dir(env)?.join("pitcrew.js"))
}

fn content(exe: &str) -> String {
    format!(
        r#"{MARKER} Safe to delete, or run: pitcrew hooks uninstall
// Forwards OpenCode's bus events to the PitCrew daemon via `pitcrew hook opencode <event>`.

import {{ spawn }} from "node:child_process";

const PITCREW = {};

function fire(eventType, payload) {{
  // The daemon only accepts event names matching [A-Za-z][A-Za-z0-9_-]{{0,63}}; OpenCode's bus
  // event names use dots (e.g. "session.idle"), so dots become underscores.
  const event = String(eventType ?? "event").replace(/[^A-Za-z0-9_-]/g, "_");
  try {{
    const child = spawn(PITCREW, ["hook", "opencode", event], {{
      stdio: ["pipe", "ignore", "ignore"],
      detached: true,
      windowsHide: true,
    }});
    child.on("error", () => {{}});
    child.stdin.end(JSON.stringify(payload ?? {{}}));
    child.unref();
  }} catch {{
    // Fire-and-forget: a notification failure must never affect the agent.
  }}
}}

export default async () => ({{
  event: async ({{ event }}) => {{
    fire(event?.type, event);
  }},
}});
"#,
        js_string(exe)
    )
}

fn js_string(s: &str) -> String {
    serde_json::to_string(s).unwrap_or_else(|_| "\"\"".to_owned())
}

pub(crate) fn plan_install(env: Env<'_>, exe: &str) -> Result<Plan> {
    let path = path(env)?;
    let before = super::read_optional(&path)?;
    let desired = content(exe);
    match &before {
        None => Ok(Plan {
            target: Target::OpenCode,
            status: Status::Missing,
            detail: format!("{} (not installed)", path.display()),
            changes: vec![Change {
                path,
                before,
                after: desired.into_bytes(),
                delete: false,
                executable: false,
            }],
        }),
        Some(bytes) => {
            let text = String::from_utf8_lossy(bytes);
            if !text.starts_with(MARKER) {
                return Ok(Plan {
                    target: Target::OpenCode,
                    status: Status::Conflicting,
                    detail: format!(
                        "{} already exists and was not created by pitcrew; move it aside first",
                        path.display()
                    ),
                    changes: vec![],
                });
            }
            if *text == desired {
                Ok(Plan {
                    target: Target::OpenCode,
                    status: Status::Installed,
                    detail: format!("{} (already installed)", path.display()),
                    changes: vec![],
                })
            } else {
                Ok(Plan {
                    target: Target::OpenCode,
                    status: Status::Installed,
                    detail: format!("{} (refreshing it)", path.display()),
                    changes: vec![Change {
                        path,
                        before: before.clone(),
                        after: desired.into_bytes(),
                        delete: false,
                        executable: false,
                    }],
                })
            }
        }
    }
}

pub(crate) fn plan_uninstall(env: Env<'_>) -> Result<Plan> {
    let path = path(env)?;
    let before = super::read_optional(&path)?;
    match &before {
        None => Ok(Plan {
            target: Target::OpenCode,
            status: Status::Missing,
            detail: format!("{} (nothing installed)", path.display()),
            changes: vec![],
        }),
        Some(bytes) => {
            let text = String::from_utf8_lossy(bytes);
            if text.starts_with(MARKER) {
                Ok(Plan {
                    target: Target::OpenCode,
                    status: Status::Installed,
                    detail: format!("{} (removing it)", path.display()),
                    changes: vec![Change {
                        path,
                        before: before.clone(),
                        after: Vec::new(),
                        delete: true,
                        executable: false,
                    }],
                })
            } else {
                Ok(Plan {
                    target: Target::OpenCode,
                    status: Status::Conflicting,
                    detail: format!("{} was not created by pitcrew; leaving it alone", path.display()),
                    changes: vec![],
                })
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn env_of(pairs: &[(&str, &str)]) -> impl Fn(&str) -> Option<std::ffi::OsString> + use<> {
        let map: std::collections::HashMap<String, std::ffi::OsString> = pairs
            .iter()
            .map(|(k, v)| ((*k).to_owned(), std::ffi::OsString::from(v)))
            .collect();
        move |name| map.get(name).cloned()
    }

    const EXE: &str = "/home/sam/.local/bin/pitcrew";

    #[test]
    fn resolves_the_plugin_directory_like_opencode_does() {
        let tmp = tempfile::tempdir().unwrap();
        let env = env_of(&[("XDG_CONFIG_HOME", tmp.path().to_str().unwrap())]);
        assert_eq!(
            plugin_dir(&env).unwrap(),
            tmp.path().join("opencode").join("plugin")
        );
    }

    #[test]
    fn installs_then_is_a_no_op_then_uninstalls() {
        let tmp = tempfile::tempdir().unwrap();
        let env = env_of(&[("XDG_CONFIG_HOME", tmp.path().to_str().unwrap())]);

        let plan = plan_install(&env, EXE).unwrap();
        assert!(plan.status == Status::Missing);
        let p = &plan.changes[0];
        std::fs::create_dir_all(p.path.parent().unwrap()).unwrap();
        std::fs::write(&p.path, &p.after).unwrap();
        let text = String::from_utf8_lossy(&p.after);
        assert!(text.contains(EXE));
        assert!(text.contains("hook"));

        let plan = plan_install(&env, EXE).unwrap();
        assert!(plan.status == Status::Installed);
        assert!(plan.changes.is_empty());

        let plan = plan_uninstall(&env).unwrap();
        assert!(plan.changes[0].delete);
    }

    #[test]
    fn a_foreign_file_is_a_conflict_on_both_sides() {
        let tmp = tempfile::tempdir().unwrap();
        let env = env_of(&[("XDG_CONFIG_HOME", tmp.path().to_str().unwrap())]);
        let p = path(&env).unwrap();
        std::fs::create_dir_all(p.parent().unwrap()).unwrap();
        std::fs::write(&p, "// someone else's plugin\n").unwrap();

        let plan = plan_install(&env, EXE).unwrap();
        assert!(plan.status == Status::Conflicting);
        assert!(plan.changes.is_empty());

        let plan = plan_uninstall(&env).unwrap();
        assert!(plan.status == Status::Conflicting);
        assert!(plan.changes.is_empty());
        assert_eq!(std::fs::read_to_string(&p).unwrap(), "// someone else's plugin\n");
    }
}
