//! `pitcrew hooks install` and `uninstall` (through `pitcrew_cli::run`) on arbitrary existing
//! agent configuration files: Claude Code's `settings.json`, Codex's `config.toml` (with and
//! without `--chain`), and OpenCode's plugin file. These are the person's own files, often edited
//! by hand or by other tools, and the hook command written into them runs on every agent turn.
//!
//! Input: a flags byte (engine; `--chain`; whether the file exists), then the file's bytes. Each
//! input gets a fresh scratch home; the executable is `/opt/pitcrew/bin/pitcrew` (the CLI's
//! test override, read only in builds with debug assertions, which `cargo fuzz` builds by default).
//!
//! Checks, besides "no panic":
//! - a refused `install` or `uninstall` leaves the file byte-for-byte as it was;
//! - **no key that isn't ours is dropped or changed**: after `install`, and after `uninstall`,
//!   everything in the file except our own entries means the same as before (JSON or TOML
//!   values; for Claude, every hook in our five events whose command is not `… hook claude
//!   <Event>`, in order; for Codex, a `notify` that isn't ours comes back exactly);
//! - `install` twice changes nothing the second time;
//! - after `uninstall`, nothing `install` wrote is left;
//! - **install then uninstall gives the original file back** when it held nothing of ours:
//!   byte-for-byte, except for Claude's documented case of empty `hooks` containers.
#![no_main]

use libfuzzer_sys::fuzz_target;
use pitcrew_cli::Io;
use pitcrew_fuzz::fresh_dir;
use serde_json::{Map, Value, json};
use std::ffi::OsString;
use std::path::{Path, PathBuf};

const EXE: &str = "/opt/pitcrew/bin/pitcrew";
const EVENTS: [&str; 5] = [
    "SessionStart",
    "UserPromptSubmit",
    "Stop",
    "SessionEnd",
    "Notification",
];
const OPENCODE_MARKER: &str = "// Generated by `pitcrew hooks install`.";
const BOM: char = '\u{feff}';

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
enum Engine {
    Claude,
    Codex,
    OpenCode,
}

impl Engine {
    fn name(self) -> &'static str {
        match self {
            Self::Claude => "claude",
            Self::Codex => "codex",
            Self::OpenCode => "opencode",
        }
    }

    fn path(self, home: &Path) -> PathBuf {
        match self {
            Self::Claude => home.join(".claude/settings.json"),
            Self::Codex => home.join(".codex/config.toml"),
            Self::OpenCode => home.join(".config/opencode/plugin/pitcrew.js"),
        }
    }
}

fuzz_target!(|input: &[u8]| {
    if !cfg!(debug_assertions) {
        // Without debug assertions the CLI ignores the executable override; nothing to check.
        return;
    }
    let Some((&flags, file)) = input.split_first() else {
        return;
    };
    let engine = [Engine::Claude, Engine::Codex, Engine::OpenCode][usize::from(flags % 3)];
    let chain = engine == Engine::Codex && flags & 4 != 0;
    let home = fresh_dir("cli-home");
    let path = engine.path(&home);
    if flags & 8 == 0 {
        std::fs::create_dir_all(path.parent().expect("a parent")).expect("create the folder");
        std::fs::write(&path, file).expect("write the config");
    }
    let before = read(&path);

    let install = |home: &Path| run(home, engine, "install", chain);
    let uninstall = |home: &Path| run(home, engine, "uninstall", false);

    let installed = install(&home) == 0;
    let after_install = read(&path);
    if installed {
        check_preserved(
            engine,
            before.as_deref(),
            after_install.as_deref(),
            "install",
        );
        check_ours_installed(engine, after_install.as_deref());
        assert_eq!(install(&home), 0, "a second install failed");
        assert_eq!(
            read(&path),
            after_install,
            "a second install changed the file"
        );
    } else {
        assert_eq!(after_install, before, "a refused install changed the file");
    }

    let uninstalled = uninstall(&home) == 0;
    let after_uninstall = read(&path);
    if !uninstalled {
        assert_eq!(
            after_uninstall, after_install,
            "a refused uninstall changed the file"
        );
        return;
    }
    check_preserved(
        engine,
        before.as_deref(),
        after_uninstall.as_deref(),
        "uninstall",
    );
    check_nothing_ours(engine, after_uninstall.as_deref());
    if installed && !possibly_ours(engine, before.as_deref()) {
        check_round_trip(engine, before.as_deref(), after_uninstall.as_deref());
    }
});

/// Runs `pitcrew --json hooks <action> --engine <engine> --yes [--chain]` and returns its exit
/// code. Backups are removed afterwards: they are named by the millisecond, and two runs in one
/// millisecond would otherwise collide.
fn run(home: &Path, engine: Engine, action: &str, chain: bool) -> i32 {
    let env = |name: &str| -> Option<OsString> {
        match name {
            "HOME" => Some(home.into()),
            "CLAUDE_CONFIG_DIR" => Some(home.join(".claude").into()),
            "CODEX_HOME" => Some(home.join(".codex").into()),
            "XDG_CONFIG_HOME" => Some(home.join(".config").into()),
            "PITCREW_INSTALL_EXE_FOR_TEST" => Some(EXE.into()),
            _ => None,
        }
    };
    let mut args = vec![
        "pitcrew",
        "--json",
        "hooks",
        action,
        "--engine",
        engine.name(),
        "--yes",
    ];
    if chain {
        args.push("--chain");
    }
    let mut stdin = std::io::empty();
    let (mut stdout, mut stderr) = (Vec::new(), Vec::new());
    let mut io = Io {
        stdin: &mut stdin,
        stdin_is_terminal: false,
        stdout: &mut stdout,
        stderr: &mut stderr,
    };
    let code = pitcrew_cli::run(
        args.into_iter().map(OsString::from).collect(),
        &env,
        &mut io,
    );
    let dir = engine.path(home);
    if let Some(Ok(entries)) = dir.parent().map(std::fs::read_dir) {
        for entry in entries.flatten() {
            if entry
                .file_name()
                .to_string_lossy()
                .contains(".pitcrew-backup-")
            {
                let _ = std::fs::remove_file(entry.path());
            }
        }
    }
    code
}

fn read(path: &Path) -> Option<Vec<u8>> {
    match std::fs::read(path) {
        Ok(bytes) => Some(bytes),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => None,
        Err(e) => panic!("cannot read {}: {e}", path.display()),
    }
}

fn text(bytes: Option<&[u8]>) -> Option<&str> {
    let text = std::str::from_utf8(bytes?).ok()?;
    Some(text.strip_prefix(BOM).unwrap_or(text))
}

fn json(bytes: Option<&[u8]>) -> Option<Value> {
    serde_json::from_str(text(bytes)?).ok()
}

fn toml(bytes: Option<&[u8]>) -> Option<Value> {
    let doc: toml_edit::DocumentMut = text(bytes)?.parse().ok()?;
    Some(toml_table(doc.as_table().iter()))
}

fn ours_command(event: &str) -> String {
    format!("{EXE} hook claude {event}")
}

/// The Claude hooks in our events whose command could be ours (`… hook claude <Event>`).
fn claude_possibly_ours(hook: &Value, event: &str) -> bool {
    hook.get("command")
        .and_then(Value::as_str)
        .is_some_and(|c| c.ends_with(&format!(" hook claude {event}")))
}

/// A Codex `notify` that could be ours: it ends with `hook codex notify` (and maybe `--chain`).
fn codex_possibly_ours(notify: &Value) -> bool {
    let Some(values) = notify.as_array() else {
        return false;
    };
    let words: Vec<&str> = values.iter().filter_map(Value::as_str).collect();
    let core = words.strip_suffix(&["--chain"]).unwrap_or(&words);
    core.ends_with(&["hook", "codex", "notify"])
}

fn possibly_ours(engine: Engine, bytes: Option<&[u8]>) -> bool {
    match engine {
        Engine::Claude => json(bytes).is_some_and(|v| {
            EVENTS.iter().any(|e| {
                v["hooks"][e].as_array().is_some_and(|groups| {
                    groups.iter().any(|g| {
                        g["hooks"]
                            .as_array()
                            .is_some_and(|hooks| hooks.iter().any(|h| claude_possibly_ours(h, e)))
                    })
                })
            })
        }),
        Engine::Codex => toml(bytes).is_some_and(|v| codex_possibly_ours(&v["notify"])),
        Engine::OpenCode => text(bytes).is_some_and(|t| t.starts_with(OPENCODE_MARKER)),
    }
}

/// Everything in a Claude settings file that is not ours: the document without our five events,
/// and, for each of them, the matcher and value of every hook that is not ours, in order.
fn claude_view(doc: &Value) -> (Value, Vec<(String, Value, Value)>) {
    let mut outer = doc.clone();
    let mut foreign = Vec::new();
    let Some(map) = outer.as_object_mut() else {
        return (outer, foreign);
    };
    if let Some(Value::Object(mut hooks)) = map.remove("hooks") {
        for event in EVENTS {
            let Some(groups) = hooks.remove(event) else {
                continue;
            };
            let Some(groups) = groups.as_array() else {
                foreign.push((event.to_owned(), Value::Null, groups));
                continue;
            };
            for group in groups {
                match group["hooks"].as_array() {
                    Some(inner) => {
                        for hook in inner.iter().filter(|h| !claude_possibly_ours(h, event)) {
                            foreign.push((
                                event.to_owned(),
                                group["matcher"].clone(),
                                hook.clone(),
                            ));
                        }
                    }
                    None => foreign.push((event.to_owned(), Value::Null, group.clone())),
                }
            }
        }
        if !hooks.is_empty() {
            map.insert("hooks".to_owned(), Value::Object(hooks));
        }
    } else if let Some(hooks) = doc.get("hooks") {
        map.insert("hooks".to_owned(), hooks.clone());
    }
    (outer, foreign)
}

/// Everything in a Codex config that is not `notify`, and `notify` if it is not ours.
fn codex_view(doc: &Value) -> (Value, Option<Value>) {
    let mut outer = doc.clone();
    let notify = outer.as_object_mut().and_then(|m| m.remove("notify"));
    (outer, notify.filter(|n| !codex_possibly_ours(n)))
}

fn check_preserved(engine: Engine, before: Option<&[u8]>, after: Option<&[u8]>, step: &str) {
    match engine {
        Engine::Claude => {
            let Some(before) = json(before) else { return };
            let after =
                json(after).unwrap_or_else(|| panic!("{step} left a file that is not JSON"));
            assert_eq!(
                claude_view(&after),
                claude_view(&before),
                "{step} changed or dropped something that isn't ours"
            );
        }
        Engine::Codex => {
            let Some(before) = toml(before) else { return };
            let after =
                toml(after).unwrap_or_else(|| panic!("{step} left a file that is not TOML"));
            let (outer_before, notify_before) = codex_view(&before);
            let (outer_after, notify_after) = codex_view(&after);
            assert_eq!(
                outer_after, outer_before,
                "{step} changed something that isn't ours"
            );
            if step == "uninstall" {
                assert_eq!(
                    notify_after, notify_before,
                    "uninstall did not restore a foreign notify"
                );
            }
        }
        Engine::OpenCode => {
            if before.is_some() && !possibly_ours(engine, before) {
                assert_eq!(
                    after, before,
                    "{step} touched a plugin file that isn't ours"
                );
            }
        }
    }
}

fn check_ours_installed(engine: Engine, after: Option<&[u8]>) {
    match engine {
        Engine::Claude => {
            let doc = json(after).expect("installed settings are JSON");
            for event in EVENTS {
                let wired = doc["hooks"][event].as_array().is_some_and(|groups| {
                    groups.iter().any(|g| {
                        g["hooks"].as_array().is_some_and(|hooks| {
                            hooks
                                .iter()
                                .any(|h| h["command"] == json!(ours_command(event)))
                        })
                    })
                });
                assert!(wired, "install did not wire up {event}");
            }
        }
        Engine::Codex => {
            let doc = toml(after).expect("an installed config is TOML");
            assert!(
                codex_possibly_ours(&doc["notify"]),
                "install did not set notify"
            );
            assert_eq!(doc["notify"][0], json!(EXE), "notify names another program");
        }
        Engine::OpenCode => {
            assert!(
                text(after).is_some_and(|t| t.starts_with(OPENCODE_MARKER) && t.contains(EXE)),
                "install did not write our plugin"
            );
        }
    }
}

fn check_nothing_ours(engine: Engine, after: Option<&[u8]>) {
    match engine {
        Engine::Claude => {
            let Some(doc) = json(after) else { return };
            for event in EVENTS {
                let left = doc["hooks"][event].as_array().is_some_and(|groups| {
                    groups.iter().any(|g| {
                        g["hooks"].as_array().is_some_and(|hooks| {
                            hooks
                                .iter()
                                .any(|h| h["command"] == json!(ours_command(event)))
                        })
                    })
                });
                assert!(!left, "uninstall left our {event} hook");
            }
        }
        Engine::Codex => {
            let Some(doc) = toml(after) else { return };
            assert!(
                doc["notify"][0] != json!(EXE) || !codex_possibly_ours(&doc["notify"]),
                "uninstall left our notify"
            );
        }
        Engine::OpenCode => {
            assert!(!possibly_ours(engine, after), "uninstall left our plugin");
        }
    }
}

fn check_round_trip(engine: Engine, before: Option<&[u8]>, after: Option<&[u8]>) {
    if engine == Engine::Claude {
        let Some(doc) = json(before) else { return };
        // Documented: empty `hooks` containers that were already there go away with ours.
        let empty = |v: &Value| v.as_object().is_some_and(Map::is_empty);
        let had_empty_container = empty(&doc["hooks"])
            || EVENTS
                .iter()
                .any(|e| doc["hooks"][e].as_array().is_some_and(Vec::is_empty));
        if had_empty_container {
            return;
        }
    }
    if engine == Engine::Codex && toml(before).is_none() {
        return;
    }
    if engine == Engine::Claude && text(before).is_some_and(|t| t.trim().is_empty()) {
        // An empty file is replaced by a fresh document; there is nothing to give back.
        return;
    }
    // Codex's installer drops a leading BOM (reported as R24; the meaning is the same), so the
    // bytes are compared without it there.
    let bytes = |b: Option<&[u8]>| {
        b.map(|b| {
            let text = String::from_utf8_lossy(b).into_owned();
            match engine {
                Engine::Codex => text.strip_prefix(BOM).map_or(text.clone(), str::to_owned),
                _ => text,
            }
        })
    };
    assert_eq!(
        bytes(after),
        bytes(before),
        "install then uninstall did not give the file back"
    );
}

fn toml_table<'a>(entries: impl Iterator<Item = (&'a str, &'a toml_edit::Item)>) -> Value {
    Value::Object(
        entries
            .map(|(k, item)| (k.to_owned(), toml_item(item)))
            .collect(),
    )
}

fn toml_item(item: &toml_edit::Item) -> Value {
    match item {
        toml_edit::Item::None => Value::Null,
        toml_edit::Item::Value(v) => toml_value(v),
        toml_edit::Item::Table(t) => toml_table(t.iter()),
        toml_edit::Item::ArrayOfTables(a) => {
            Value::Array(a.iter().map(|t| toml_table(t.iter())).collect())
        }
    }
}

fn toml_value(value: &toml_edit::Value) -> Value {
    match value {
        toml_edit::Value::String(s) => json!(s.value()),
        toml_edit::Value::Integer(n) => json!(n.value()),
        toml_edit::Value::Float(f) => json!(format!("{:?}", f.value())),
        toml_edit::Value::Boolean(b) => json!(b.value()),
        toml_edit::Value::Datetime(d) => json!(d.value().to_string()),
        toml_edit::Value::Array(a) => Value::Array(a.iter().map(toml_value).collect()),
        toml_edit::Value::InlineTable(t) => Value::Object(
            t.iter()
                .map(|(k, v)| (k.to_owned(), toml_value(v)))
                .collect(),
        ),
    }
}
